### ISSUE TITLE
Can not use rebar3 to build plugin.

### ISSUE THREAD

**Issue by dcy** [erlio/vernemq#133]
Hi!
The plugin use rebar3 will be: 
```
vernemq$ ./bin/vmq-admin plugin enable --name hisir_plugin --path /home/dcy/app/hisir_plugin
Can't enable plugin: hisir_plugin due to plugin_not_found
```
But if use rebar, it works.

The same as [vernemq_demo_plugin](https://github.com/dergraf/vernemq_demo_plugin)
```
rm -rf rebar deps ebin
rebar3 compile
```
It will be:
```
vernemq$ ./bin/vmq-admin plugin enable --name vernemq_demo_plugin --path /home/dcy/app/vernemq_demo_plugin
Can't enable plugin: vernemq_demo_plugin due to plugin_not_found

```

**Comment by larshesel** [comment]
Hi there, thanks for reporting. To use a rebar3 generated plugin, the path should be:

    /home/dcy/app/vernemq_demo_plugin/_build/default 

This is because the plugin code looks for OTP applications in `ebin`, `deps/*/ebin` (rebar) and `lib/*/ebin`(rebar3) subdirectories of the path given.

We should probably document this better, so thank you for bringing this to our attention!

**Comment by dcy** [comment]
Thanks!
Maybe you should document how to enable and how to upgrade plugin online
