### ISSUE TITLE
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed

### ISSUE THREAD

**Issue by liucy2007975** [erlio/vernemq#137]
I have 100 clients connected to the vernemq cluster for a day, and I saw the vernemq console have a lot of error message with:
.......
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
08:54:25.238 [error] Error in process <0.17397.3> on node 'VerneMQ_5@192.168.3.180' with exit value: {{badmatch,{error,timeout}},[{cpu_sup,measurement_server_init,0,[{file,"cpu_sup.erl"},{line,546}]}]}
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
08:54:49.120 [error] Error in process <0.17404.3> on node 'VerneMQ_5@192.168.3.180' with exit value: {{badmatch,{error,timeout}},[{cpu_sup,measurement_server_init,0,[{file,"cpu_sup.erl"},{line,546}]}]}
.......

It shows every  20~25s .  what's the reason ? what's the error mean?

**Comment by larshesel** [comment]
Hi, this sounds strange and is definitely not something that is normal. I don't know what the error means exactly, but it looks like the cpu supervisor is getting a timeout when trying to start or do a measurement and chrashes due to a timeout.

To maybe get closer to understanding the issue could you provide us with a bit more information:

- could you show us the error and crash log files? Maybe there's some additional information in there.

- Which OS are you running on?

- Do you see these errors immediately after starting the node or do they show after a while?

- Are you running on a single-core or multi-core system?

Cheers,
Lars

**Comment by larshesel** [comment]
Hi, just to clarify, `cpu_sup` is an internal tool used to monitor CPU load. These messages are harmless for the operation of VerneMQ. We've added a task on our backlog to make these errors not show in the future.

**Comment by MosesMuiru** [comment]
is there a solution to this?

**Comment by ioolkos** [comment]
@MosesMuiru https://github.com/erlang/otp/pull/6689 might be

---
👉 Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
👉 Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
