### ISSUE TITLE
Subscribe after reconnect may duplicate subscription

### ISSUE THREAD

**Issue by mtappler** [erlio/vernemq#157]
This issue is related to #155 but not the same. 
I am currently investigating the behaviour of several MQTT-brokers in an automated manner and so I occasionally come across odd test sequences, like the following. Although it is probably not a normal use case, it may reveal unwanted behaviour.

I connect with a client with client identifier `"Client1"` then I subscribe to a topic `"my_topic"`. Afterwards I open another TCP-connection and connect with client identifier `"Client1"` again (this time with a non-clean session). Everything works as expected: the first client gets disconnected and a new connection is established.

I again subscribe to the topic `"my_topic"` with the reconnected client. In a last step I publish a message `"i_am_the_second_client"` to `"my_topic"` with QoS 0. In response to that I receive this message twice. 

I would actually expect to receive `"i_am_the_second_client"` only once which I think is in line with the MQTT-specification as new subscription should replace existing ones. 

I checked this with the latest version of VerneMQ on Ubuntu 14.04.

**Comment by ioolkos** [comment]
Thanks!

OK, so this is with clean_session false, so that the subscriptions get persisted. 
Do your clients automatically re-connect? I guess not, as you'd probably seen that. But with a re-connecting client like `mosquitto_sub`, this creates 2 connections racing each other anyway.

We'll check. 
Thanks so much for your effort! :) super useful.

**Comment by mtappler** [comment]
I actually wrote my own simple MQTT-client library to have maximum control over what is sent. I also do so because I want to see the behaviour of the broker and not the composition of broker and client library which might do stuff I don't want.
So when I say that I connect to the broker, then I create a new TCP/IP-connection and send a CONNECT-packet and nothing else, i.e. no further checks. 

You are welcome! 
Thanks for fast responses!

**Comment by ioolkos** [comment]
OK, yes that's the best way to do it. (although there's a lot a CONNECT-packet actually configures).

Which also brings me to think about the Session Present flag. Because if one is present on the server, then the client can basically decide what it wants to do with it (throw it away or taking it). But yeah, it's still valid for the client to subscribe to the same topic again.

**Comment by mtappler** [comment]
I have some additional information. Since you mentioned that subscribing again is valid, I checked whether different QoS-levels had an impact as chosing a different QoS-level would be a use case. They actually have an impact: if I subscribe first with QoS 1 (0) and then with 0 (1), i.e. the other one, I receive the message twice. However, if I subscribe both times with the same QoS, either 1 or 0, I receive the message only once.

**Comment by ioolkos** [comment]
Ha, yes.

Spec: 

"When Clients make subscriptions with Topic Filters that include wildcards, it is possible for a Client’s subscriptions to overlap so that a published message might match multiple filters. In this case the Server MUST deliver the message to the Client respecting the maximum QoS of all the matching subscriptions [MQTT-3.3.5-1]. In addition, the Server MAY deliver further copies of the message, one for each additional matching subscription and respecting the subscription’s QoS in each case."

So, I guess this is open to interpretation. I conclude that a duplicate message at least wouldn't be wrong, if a client subscribes to the same topic, once with QoS 1 and once with QoS 2.

**Comment by mtappler** [comment]
This portion of the spec. considers Topic Filters with wildcards, but my Topic Filters do not include wildcards.

I was thinking that the following portion of the spec. would take effect here (as I have sent identical Topic Filters):
> If a Server receives a SUBSCRIBE Packet containing a Topic Filter that is identical to an existing
Subscription’s Topic Filter then it MUST completely replace that existing Subscription with a new
Subscription. The Topic Filter in the new Subscription will be identical to that in the previous Subscription, although its maximum QoS value could be different. Any existing retained messages matching the Topic Filter MUST be re-sent, but the flow of publications MUST NOT be interrupted [MQTT-3.8.4-3].

However, it doesn't hurt that much to receive some message twice of course.

**Comment by ioolkos** [comment]
You're correct... this seems to say that QoS is somehow exterior to the topic filter. 

So yes, we have to look into this :)

**Comment by mtappler** [comment]
I hope I am not bothering, but I found another related portion of the specification: 
> If CleanSession is set to 1, the Client and Server MUST discard any previous Session and start a new one. This Session lasts as long as the Network Connection. State data associated with this Session MUST NOT be reused in any subsequent Session [MQTT-3.1.2-6].

Hence, the first subscription should be deleted when the first client is disconnected, since the session should last long as the network connection. 

I came across this when looking at a shorter test sequence which does not include the second subscribe.

**Comment by ioolkos** [comment]
Your input is welcome! :) 

For clean session = true, yes, the case is clear.

**Comment by larshesel** [comment]
Track issue on vmq_server: erlio/vmq_server#70
