### ISSUE TITLE
Cluster design

### ISSUE THREAD

**Issue by anphung** [erlio/vernemq#184]
Hi,

Is there any place I can read about the inside VerneMQ cluster design? How the messages are distributed among nodes? How does it scale?
I have searched the main website but could not find any.

Sorry in case the question is not suitable for posting here.

Thank you.

**Comment by ioolkos** [comment]
Hi @anphung, good question! :)

The basics are this: 
- Messages distribution goes over dedicated TCP connections between cluster nodes
- Messages are only distributed to cluster nodes that actually need the message because they have local subscribers.
- Subscriber information is held in a replicated subscriber store based on LevelDB.
- The replication of the subscriber store is done over plumtree, an epidemic broadcast gossip protocol
- Every cluster node builds a routing tree in RAM from the subscriber store, to know where to route messages to. This looks different on every node in contrast to the replicated LevelDB store.

Possible scalability bottlenecks are:
- Constant high rates of incoming new subscribers
- Constant high rates of triggered queue migration between nodes (triggered by the same clients logging in to different cluster nodes)

Only tests can show, if a specific cluster can run the numbers you have in mind.
Don't hesitate to ask for more information anytime!

Thanks.

**Comment by anphung** [comment]
Thank you for your detailed answer.

**Comment by prettynatty** [comment]
hi @ioolkos,
does replicated subscriber store mean that qos1 and qos2 messages won't be lost on cluster node leave?
