### ISSUE TITLE
vernemq re-publishes sometimes messages

### ISSUE THREAD

**Issue by mradstake** [erlio/vernemq#195]
I am running Vernemq as a single-node setup (release details are attached).
When the load goes up (about 30 messages per second) occasionally some messages are published more than once towards a subscribed node.

The re-publish happens pretty soon (within 250ms).
At that moment the publish-ack hasn't been received yet.

I've enclosed PCAP-traces which shows the behavior.
For example packet 815 and 821 publish the same message (message ID: 65134).
The publish-ack is visible in packet 827 and 832.
Similar behaviour for message ID: 64992 (packets 687/704 - 704/724)

I have also captured the messages which are published towards Verne (not attached).
In that trace I can clearly see that the message is only sent once.

Unfortunately I don't see anything being logged in VerneMQ.
The configuration is enclosed.

[release.txt](https://github.com/erlio/vernemq/files/449447/release.txt)
[MQTT-VerneToDB.zip](https://github.com/erlio/vernemq/files/449450/MQTT-VerneToDB.zip)
[config.txt](https://github.com/erlio/vernemq/files/449466/config.txt)

**Comment by dergraf** [comment]
@mradstake hi there, thanks for reporting

The re-published messages have the 'DUP' flag set, which means they were retried by the broker. I've seen in your config `retry_interval=1000`, which of course should be enough for this scenario. However I've the feeling that our internal retry-mechanism doesn't handle this properly. Can you adjust it to e.g. `20000` and see if the error remains?

Btw, you're still on 0.12.5, we recommend to upgrade to 0.14.1.

Best
Andre

**Comment by mradstake** [comment]
Hello Andre,

I verified the behavior with retry_interval=20000 (on 0.12.5). The re-publish issue seems to be gone now.
I am actually wondering why it behaves differently compared to when it was set to 1000  ?

Besides, we are planning to upgrade to the latest version.
Will this make a difference regarding the retry mechanism?

Best regards,
Marcel

**Comment by dergraf** [comment]
Hello Marcel,

thanks for update. 

We had to implement our own timer wheel as the Erlang timer resolution is one millisecond. As a result multiple messages being retried within the same millisecond were delivered in the wrong order. In order to reduce 'timer-load' on the system we implemented a timer wheel that sticks to a 1 second resolution but guarantees that the messages are delivered in the correct order. The value of 1 second was chosen because it is a small enough time window to serve most MQTT/IoT use cases and big enough to keep the overhead of 100k+ firing timers at a minimum.

As I said earlier this doesn't explain the issue you've experienced. I am pretty sure this is a bug which we'll address soon. For the moment we'd appreciate if you can work around this issue by setting a higher `retry_interval`. We'll track the issue over here https://github.com/erlio/vmq_server/issues/94

Thanks for reporting once again, and please ping us if you run in any other issue.

Cheers,
Andre

**Comment by dergraf** [comment]
Hi Marcel, great the workaround is working.
We had to implement an own timer wheel due to the way Erlang is firing the timers.  I
