### ISSUE TITLE
Plugin Development Guide

### ISSUE THREAD

**Issue by dergraf** [erlio/vernemq#2]
Write a plugin development guide

**Comment by donileo** [comment]
Hi dergraf, great mqtt server in vernemq.

I have a question. How do I go about integrating some additional functionality into the server. For example: I want to be able to detect when a mobile client gets disconnected and then proceed to send Push notifications (APNS) to them. In my specific case my API is using Go and it already knows about the endpoints so essentially im looking for a way to detect client disconnection and then allow vernemq to pass all those messages intended for that disconnected client onto my Go API so that it can send it via APNS until they go online again.

**Comment by dergraf** [comment]
Hi donileo,

that's an interesting use case, which is currently not possible using the plugin infrastructure. However if you are not afraid of hacking VerneMQ yourself it is actually reimplementing https://github.com/erlio/vmq_server/blob/master/src/vmq_msg_store.erl#L175. But, wouldn't it be more useful to just awake your client in this case and deliver the messages once it reconnects via MQTT?

**Comment by donileo** [comment]
Hi dergaf,

The problem is that on iOS when backgrounding the app embedded with the MQTT client the connection must be terminated so the app cannot run in the background. I guess this bypasses part of the need of the need for using mqtt in the first place but the only way to get the ability to run in the background with ios is by classifying your app as a voip app. Once the app is in the background - no longer running - it must still receive the mqtt messages which in my case are chat messages via push, so thats the reason for this question.

**Comment by dergraf** [comment]
I've just recently learned about this possibility to specify the app as a voip app, as you said. Wouldn't this solve your problem or would you still need apple/android push?

**Comment by donileo** [comment]
No I think it'd be good to still have the apple/android push. Many apps are not true voip apps so they cant classify themselves as such.

**Comment by dergraf** [comment]
I see. Wouldn't it be possible to just wake up the IoS/Android application, which then reconnects and receives all the outstanding messages?

**Comment by PedroAlvarado** [comment]
For mobile apps using MQTT, it is useful to know when a client disconnected. As donileo mention, in the case of a disconnect, one could trigger a number of things when that happens including messaging the user/device via different mediums (e.g APNS). I'd be great if vernemq had a hook to detect client disconnects.

@donileo IOS 7 has two new background execution modes: fetch and remote-notification. This could help address your use case.

**Comment by leoyey** [comment]
@dergraf I cannot find https://github.com/erlio/vmq_server/blob/master/src/vmq_msg_store.erl code anymore. Where did it go?

Thanks for your help!

**Comment by dergraf** [comment]
@leoyey that's gone (refactored out), check the changelogs for this. If you're implementing your own message store, check vmq_lvldb_*.erl modules. The message store backend is initialized and started by the msg_store_childspecs env variable. 

    {msg_store_childspecs, [{vmq_lvldb_store_sup,
                                   {vmq_lvldb_store_sup, start_link, []},
                                   permanent, 5000, supervisor, [vmq_lvldb_store_sup]}]},

**Comment by leoyey** [comment]
@dergraf Thanks for your quick response! I am not intend to implement a message store. I am facing the same problem as @donileo . I want to know whether the client is disconnected or not, so I can send a push notification (e.g APNS) to it if it is offline. The push notification just notify the user that he has a new message. When he open the apps again, it will reconnect the MQTT broker and get the message. Could you help to advise where should I hack in?

**Comment by dergraf** [comment]
ah I see.. yeah there are a couple of hooks still missing.. I think this is one of those. If you need it today then no clean solution exist. However if you can wait a few weeks until the next release I could implement the hooks.

**Comment by leoyey** [comment]
@dergraf Thanks for you information. When do you plan to release the next version of VerneMQ?

**Comment by leoyey** [comment]
@dergraf I don't know if it is possible, but it would be great if you can provide a hook which will get called before/after the message send to clients. If multiple clients subscribe the same topic, then the hook will be called multiple times.
If we have this hook, then I just need to implement it and send the notification if the client is offline. For online clients, the hook will do nothing.

**Comment by dergraf** [comment]
long time overdue... finally the plugin guide is here. https://verne.mq/docs/plugin_development.html
