### ISSUE TITLE
Clustered Mode: Two clients connecting with the same ID.

### ISSUE THREAD

**Issue by testark** [erlio/vernemq#201]
I have a three node setup of VerneMQ and I'm able to connect two clients with the same ID simultaneously on different nodes (but not on the same). Can you reproduce this?

**Comment by ioolkos** [comment]
Hi @testark :)
How are the nodes configured (`allow_multiple_sessions` and `trade_consistency`)? Do you connect with clean_session 0?
What is the shortest series of CONNECTS and SUBSCRIBES to reproduce this?

**Comment by testark** [comment]
@ioolkos I'm using the default configuration:

```
trade_consistency = off
allow_multiple_sessions = off
```

I'm connecting with clean session set to false. No `SUBSCRIBE`s are needed. You only need to set up three clustered nodes (I believe two clustered nodes would be enough) and issue one `CONNECT` to each different node.

**Comment by ioolkos** [comment]
OK, thanks @testark.

I think this might be related to a queue migration race that we had prior to 14.2. (are you using the latest version?)

Do your clients constantly re-connect without you realizing?

**Comment by testark** [comment]
@ioolkos

> are you using the latest version?
Yes, I'm using 0.14.2

> Do your clients constantly re-connect without you realizing?
No, this was a controlled experiment.

**Comment by ioolkos** [comment]
Ok, confirmed, introduced this bug with the new queue migration stuff.
This seems to be wrongly enforced right now upon SUBSCRIBE, not upon CONNECT with the same ClientID. (you can see this, if you issue a subscription for one of those connections)
Working on a fix.

Thanks @testark!

**Comment by testark** [comment]
Most welcome @ioolkos :-)

**Comment by dergraf** [comment]
Let's track this over here https://github.com/erlio/vmq_server/issues/100

**Comment by dergraf** [comment]
@testark we merged a fix for this in erlio/vmq_server#100. The fix involves a change of the internal persisted subscriber data structure. An upgraded node will automatically migrate old versions of the data structure to the new format.

We'd appreciate your feedback. Just do an `rebar3 upgrade vmq_server && make rel` on a node to test the fix.

**Warning:**
The fix doesn't contain an upgrade plan for a clustered setup. This requires all nodes to run the same version of the vmq_server application, otherwise cross-node publishing and queue-migration isn't working.
