### ISSUE TITLE
Elaboration and Documentation for 'terminate due to remote_node_not_available' error

### ISSUE THREAD

**Issue by rstephen** [erlio/vernemq#203]
Thanks for an interesting product! I am evaluating vernemq as our companies MQTT broker. I'm migrating away from RabbitMQ due to some memory issues and lack of retained messages across nodes support. 

I'm using VerneMQ 0.14.2 installed from deb package on Ubuntu 14.04.5

I had the same 2 node setup as in issue #52 and I was using FQDN in my nodenames. I had the same `terminate due to remote_node_not_available error` errors in my console.log even though cluster status looked good. 

Subscribers only saw messages if they were subscribed to the node that received the message. 

"Changing listener.vmq.clustering from 0.0.0.0:44053 to something like 192.168.10.123:44053" on both nodes resolved the issue; subscribers on both nodes received all the messages. 

Can you elaborate on why this resolved the issue? Seems like using `0.0.0.0` should have worked and would be a little easier for if/when we need to scale since I like to clone VMs.

This might be a good thing to add to the clustering documentation and the `vernemq.conf` section comments since it took a bit of searching to resolve after following the clustering guide.

**Comment by ioolkos** [comment]
Thanks @rstephen!
I'll look into this tomorrow & make the documentation better. Right now, I do not remember what causes the troubles with 0.0.0.0.

**Comment by dergraf** [comment]
If I remember correctly we saw some issues with binding to `0.0.0.0` if VerneMQ is running in some sort of virtualized environment. @rstephen are you running the cluster on virtualized nodes?

**Comment by rstephen** [comment]
Thanks @dergraf! 
Yes, I am running the nodes on AWS instances.

**Comment by ioolkos** [comment]
OK, I suppose you have the cluster nodes in the same security group. 
Do you allow all traffic within those nodes? could the root casue be some other configuration with security groups?

**Comment by rstephen** [comment]
Both nodes are in the same security group. I had the ports outlined in the clustering guide open at first within the security group and I set the erlang minimum and maximum ports in the vernemq config as suggested. I later opened all traffic within the security group to see if there was a port I missed of if the min/max port setting wasn't having an affect. I still had the same issue until I set the `listener.vmq.clustering` to each node's private ip address.

**Comment by rstephen** [comment]
I might add that the 2 nodes are on different subnets (and availability zones) but I didn't see any issues accessing the ports from one node to another.

**Comment by ioolkos** [comment]
We have at least an explanation for the 0.0.0.0 problem. 

The fact is that 0.0.0.0 starts listener on all interfaces. We're already clustered (over the Erlang Port Mapper Daemon), so we even can get all the IP interfaces and addresses from the other node. But we can't decide from the calling node, which one of these IP addresses is actually meant for message distribution. That's why you have to actually decide yourself (ie configure the vmq listener yourself).

We could select an IP randomly for you, among the given 0.0.0.0 interfaces. But I don't think that's the better solution. From our side, it was basically a bad idea to even write "0.0.0.0" in the vernemq.conf as a default.

The correct way is probably some sort of automated deployment, where you can ask the EC2 instance for its internal IP via API call & then set the vmq listener to that.

Than you for your help @rstephen!

**Comment by rstephen** [comment]
Thanks @ioolkos, that's helpful information and a great idea.
