### ISSUE TITLE
VerneMQ fails to deliver message with vmq_mqtt_fsm:connected warning

### ISSUE THREAD

**Issue by anonymouse64** [erlio/vernemq#248]
Hi,
I'm running VerneMQ on Ubuntu Xenial and using the nightly build, and I am consistently running into the following error when 2 messages are published with a single subscriber on a given topic:
```
2016-12-28 21:27:32.766 [warning] <0.529.0>@vmq_mqtt_fsm:connected:260 subscriber {[],<<"mosqsub/24945-ijohnson2">>} dropped 2 messages
```

The subscribing client also doesn't receive any of the messages (the subscriber being `mosqsub/24945-ijohnson2`). Any idea what might be causing this or a fix?

The following are my relevant config settings
```
max_online_messages = 0
max_inflight_messages = 0
max_offline_messages = -1
message_size_limit = 0
```

I have tried deleting `/var/lib/vernemq/*` before running VerneMQ and I still get the same behavior. 

Thanks,
Ian

**Comment by dergraf** [comment]
Hi

Max_online_messages=0 will drop every message, use -1 for no limit or any
other value that makes sense for you.


Am 28.12.2016 10:52 nachm. schrieb "Ian Johnson" <notifications@github.com>:

Hi,
I'm running VerneMQ on Ubuntu Xenial and using the nightly build, and I am
consistently running into the following error when 2 messages are published
with a single subscriber on a given topic:

2016-12-28 21:27:32.766 [warning] <0.529.0>@vmq_mqtt_fsm:connected:260
subscriber {[],<<"mosqsub/24945-ijohnson2">>} dropped 2 messages

The subscribing client also doesn't receive any of the messages (the
subscriber being mosqsub/24945-ijohnson2). Any idea what might be causing
this or a fix?

The following are my relevant config settings

max_online_messages = 0
max_inflight_messages = 0
max_offline_messages = -1
message_size_limit = 0

I have tried deleting /var/lib/vernemq/* before running VerneMQ and I still
get the same behavior.

Thanks,
Ian

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/erlio/vernemq/issues/248>, or mute the thread

**Comment by anonymouse64** [comment]
That seems to fix my issue. 

Did this value's documentation change? The default config file from a previous version that I have been using says this:

```
## The maximum number of messages to hold in the queue above
## those messages that are currently in flight. Defaults to 1000. Set to 0 for
## no maximum (not recommended). This option allows to control how a specific
## client session can deal with message bursts. As a general rule of thumb set
## this number a bit higher than the expected message rate a single consumer is
## required to process.
##
## Default: 1000
##
## Acceptable values:
##   - an integer
```

**Comment by dergraf** [comment]
Yeah this is wrong, but has been fixed a while ago. Which version are you
using?

%% @doc The maximum number of messages to hold in the queue above
%% those messages that are currently in flight. Defaults to 1000. This
affects
%% messages of any QoS. Set to -1 for no maximum (not recommended).
%% This option allows to control how a specific client session can deal
%% with message bursts. As a general rule of thumb set
%% this number a bit higher than the expected message rate a single
consumer is
%% required to process. Note that setting this value to 0 will totally block
%% delivery from any queue.

Am 28.12.2016 11:44 nachm. schrieb "Ian Johnson" <notifications@github.com>:

**Comment by anonymouse64** [comment]
I think my copy of the config file that I have been using to overwrite the installed one is from 0.12p5. I am thinking that I should just merge all my settings with a more current one then so all the documentation is actually accurate inside the file.
