### ISSUE TITLE
Retained messages not being retained ( 0.15.2-1, x64, ubuntu server)

### ISSUE THREAD

**Issue by vladbabii** [erlio/vernemq#250]
* ubuntu 16.04 server minimal (lxc container under proxmox 4.3)
* installed with dpkg -i vernemq_0.15.2-1_amd64.deb
* modified nodename to VerneMQ@<lan_ip>
* added listener.tcp.bla = <lan_ip>:1883
* set allow_anonymous = true

ran in window(1)
mosquitto_sub -t # -v -h <ip>

ran in window(2)
mosquitto_pub -h <ip> -t bla -m bla
=> see "bla bla" in window(1)

ran in window(2)
mosquitto_pub -h <ip> -r -t bla -m bla
=> see "bla bla" in window(1)

disconnect in window(1)
mosquitto_sub -t # -v -h <ip>
=> no messages seen

I don't think I', doing something wrong. I tested with mqtt nodejs library and two mosquitto clients on windows. 

I also joined two nodes in a cluster and the behaviour was the same (with or without *_netsplit options set to on)

Do i need to install anything else except the deb ?

uname -a
Linux <host> 4.4.19-1-pve #1 SMP Wed Sep 14 14:33:50 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux

installed packages - http://pastebin.com/As8YrJR3

I'll try with nightly a bit later if I have the time.

**Comment by vladbabii** [comment]
apt-get purge vernemq
rm -rf <store dir that purge doesn't delete>
rm -rf /etc/vernemq

reboot 

dpkg -i vernemq_0.15.2-8a8bf6b6-1_amd64.deb

then in vernemq.conf 
listener.tcp.other = <nlan ip>:1883
allow_anonymous = on

vernemq start

mosquitto_sub -h .. -t # -v
=> got ALL retained messages from the prior install ????

Retained messages seem to work fine now. Is 0.15.2 broken ?

**Comment by ioolkos** [comment]
Hi @vladbabii
It's hard to tell, what was going on there. You should'nt receive double messages ("bla bla").

in cases like this, I normally try to make sure that my understanding of all things is correct.

do I understand client behaviour?
do I understand that a retain message is what I think it is (and not normal offline messages for example)
what do I think should happen, and am I sure this is a correct expectation.
Was there only one VerneMQ process running?
If you stop VerneMQ, is port 1883 really closed (telnet to it!)

The things you mention should all be working correctly (although 0.15.2 has a couple known bugs fixed in nightly), in any case, but testing 'nightly' would be great, to make sure.
Thanks for testing, Vlad! :)

**Comment by vladbabii** [comment]
I ran the same steps with mosquito and mosca and they all behaved as the nightly. Also "bla bla"  is "topic message"  with mosquitto sub when using verbose - v flag. Without it you only get "message". 

I'll stick with nightly until next version.

**Comment by ioolkos** [comment]
OK, thanks for clearing up my misunderstanding!

**Comment by larshesel** [comment]
Hi @vladbabii we did fix a bug concerning retained messages since 0.15.2 was released in PR #237 - we'll see if we can't make a new release this week containing that and other fixes. Since retained behaviour is working for you as expected in the nightly I'll close this for now.
