### ISSUE TITLE
Enhancement: add more connection details in auth_on_register_hook

### ISSUE THREAD

**Issue by kellycampbell** [erlio/vernemq#308]
### Environment

- VerneMQ Version: 1.0.0rc2
- OS: Ubuntu 16.04

### Feature Request

We would like to be able to use more details about the connection in the auth plugins. Specifically, the listener it came from, e.g. local server host and port. Also, we'd like to know if the username came from a client cert or directly. If we have the listener port, then we can figure this out for ourselves, but I think it would be a simple addition to the plugin params either way.

The reason for needing this is we plan to use client certificate authentication for certain types of clients, and regular auth for others using different listener ports.

Additional thought: are the plugin interfaces as they're implemented now expandable to add new options without breaking backwards compatibility? You may want to have it take a structure or list instead of individual options for future-proofing compatibility of third party plugins.

**Comment by kellycampbell** [comment]
Upon further study, it looks like the listener has a mountpoint option for this purpose. Is that the correct use for that parameter?

**Comment by dergraf** [comment]
Hi Kelly. 
The main purpose of Mountpoint is to put clients in different groups by mounting them to completely different topic trees (name it multi tenancy). However, this feature could be used in exactly the way you have described, but your plugin must ensure that it overrides the mountpoint to a common one (such as "") unless you really want multi tenancy.

**Comment by larshesel** [comment]
Regarding the plugin interfaces we do have an idea how to extend them (in a backwards compatible way) if need be, but decided not to change anything for the 1.0 release.

Let us know if you have other questions :)

**Comment by kellycampbell** [comment]
It looks like you can't modify the mountpoint from the auth_on_subscription hook, but can from the auth_on_publish. Am I correct in this assesment (from vmq_plugin_util:check_modifiers). Is this an oversight or intentional?

I'd like to be able authenticate what topics a client can subscribe to based on which listener they connect to. Example: external devices can only subscribe to their specific queue, but a backend server can subscribe to all queues.

I can probably work around this, but it seems like auth_on_sub should be able to modify same things auth_on_pub can.

**Comment by dergraf** [comment]
Hello @kellycampbell 
Sorry for the delay, but as the issue was already closed it wasn't on our radar any more.

The possibility to modify the mountpoint in an `auth_on_publish` hook is intentional as it enabled to do cross-mountpoint publishing... which could be useful. A sort of a lightweight shovel (shoveling messages froim one mount to the other). Rewriting the mountpoint in `auth_on_subscribe` is currently not possible, and actually quite hard to implement from a technical point of view, as the underlying data model prevents a single client to be subscribed to different mountpoints.

But, what you want to achieve is still possible, without the requirement to rewrite mountpoints in `auth_on_subscribe`. E.g.:

```erlang
auth_on_subscribe({Mountpoint, ClientId}, ........) ->
    case Mountpoint of
        "" -> check_topic(Topic);
        "othermp" -> check_topic(Topic)
   ...
```

Hope this makes sense!

Cheers
