### ISSUE TITLE
on_client_gone will be triggered multiple times after reload lua script

### ISSUE THREAD

**Issue by funwun** [erlio/vernemq#348]
### Environment

- VerneMQ Version: 1.0.0

If I reload the lua script, and the on_client_gone will be triggered multiple times as same as reload times

**Comment by funwun** [comment]
unload and load is ok, but reload will trigger this issue

**Comment by larshesel** [comment]
Hi, I cannot reproduce this. I wrote this small script:

```lua
function auth_on_register(reg)
   print("auth_on_register")
   return true
end

function on_client_gone(reg)
   print("on_client_gone")
end

function on_client_offline(reg)
   print("on_client_offline")
end


hooks = {
   auth_on_register = auth_on_register,
   on_client_gone = on_client_gone,
   on_client_offline = on_client_offline
}
```

and then connected with `mosquitto_sub -d -t 'topic'` and reloaded the script with `_build/default/rel/vernemq/bin/vmq-admin script reload path=`pwd`/test.lua` but the `on_client_gone` hook isn't called and neither is the `on_client_offline`. When I kill the client the I get the `on_client_offline` hook. 

Could you provide some more information about when you experience this? Since you're getting the `on_client_gone` hook, you must have set `allow_multiple_session = on`? Also, could you post your script so we could have a look?

**Comment by larshesel** [comment]
Aah, now I see what you mean - each reload causes the hook to be registered an extra time and then when the client disconnects the hook is executed too many times. I've now done a reload 3 times and the `on_client_offline` hook get's called 3 times when a client disconnects. Thanks for reporting - we'll see if we can get this fixed soon.

**Comment by funwun** [comment]
Thanks for quickly fix.
