### ISSUE TITLE
vernemq stop command fails

### ISSUE THREAD

**Issue by inelukik** [erlio/vernemq#358]
### Environment

- VerneMQ Version: 1.0.0-1
- OS:ubuntu 16.04.4
- Erlang/OTP version (if building from source):

### Expected behavior
 The 'sudo vernemq stop' command should stop vernemq

### Actual behaviour
It does not stop vernemq, instead is dumping a error seems to hang.
{badrpc,{'EXIT',{{badfun,#Fun<erl_eval.20.52032458>},
                 [{erlang,apply,2,[]},
                  {rpc,'-handle_call_call/6-fun-0-',5,
                       [{file,"rpc.erl"},{line,206}]}]}}}

Please also advice for a workaround

**Comment by ioolkos** [comment]
Hi @inelukik 
Thanks! this happens when you have both a VerneMQ installed as a package and are running a manually installed version. The package `vernemq` command then tries to stop the other running instance which it can't.

(you can stop it with the `vernemq` command that is in the local `_build/default/rel/vernemq/bin/` path though)

Hope this makes sense.

**Comment by inelukik** [comment]
Thanks, that was the case it was manually started, So problem solved.
