### ISSUE TITLE
can't register client   due to reason not_ready

### ISSUE THREAD

**Issue by bayuemu** [erlio/vernemq#36]
I have tow vernemqs be clustered, use nginx  tcp proxy ,if one vernemq is down, other vernemq is not work , console print " can't register client  {[] xxxx} due to reason not_ready "
why?

**Comment by dergraf** [comment]
Yeah, this is because of the enabled consistency features. From VerneMQs perspective it looks like either the Node is down, or a network problem separates your two nodes. By default VerneMQ trades availability for consistency. Which means that VerneMQ will stop serving requests (CONNECT and PUBLISH) and therefore favors consistency, e.g. uniqueness of client-ids among all cluster nodes. 

But, you can CHANGE this behaviour, by trading consistency for availability!

What are you giving up if you trade consistency for availability:

Define ``trade_consistency = on`` in ``vernemq.conf`` this will allow that your currently registered clients can still publish/consume messages, but new clients CAN'T register because VerneMQ 'tries' to ensure uniqueness of the client-ids in the cluster.

Define ``allow_multiple_sessions = on`` in ``vernemq.conf`` this will allow multiple clients connecting to the cluster using the same client-id. Therefore they share the same subscriptions.


Depending on your use case, combined with proper authentication/authorization, trading consistency might be a good thing. It is definitely useful for a high-availability cluster setup.

Please check https://verne.mq/docs/clustering.html#dealing-with-network-partitions, to make sure you understand the consequences.

**Comment by bayuemu** [comment]
thinks ，I try it

**Comment by bayuemu** [comment]
run ok !  thinks

**Comment by vedavidhbudimuri** [comment]
Hey @dergraf 

Im also facing same issue while hosting two vernemq nodes as two docker containers in an ec2. 
each node is responding to other's ping request, so I guess they are connected.
I have added the logs in the image below. 

PFA
<img width="1327" alt="screen shot 2017-08-21 at 3 25 38 pm" src="https://user-images.githubusercontent.com/6457019/29514129-0e62cec6-8685-11e7-9779-60e9967ba1ed.png">

**Comment by larshesel** [comment]
@vedavidhbudimuri this happens when your cluster is partitioned. Check the cluster state using `vmq-admin cluster show`.

**Comment by vedavidhbudimuri** [comment]
@larshesel vmq-admin cluster show

shows that two of the nodes true and rest of other nodes to be false, is the issue because of that?
Initially, I tried with 6 nodes and later scaled down to two nodes.

**Comment by larshesel** [comment]
Yes, that's the problem. You have to explicitly tell VerneMQ that the nodes are gone, otherwise VerneMQ has no idea that this isn't a netsplit situation. See http://vernemq.com/docs/clustering/.

**Comment by vedavidhbudimuri** [comment]
Oops, I missed this. Thank you @larshesel

**Comment by nmarcetic** [comment]
@larshesel @dergraf Is this mean that I can't' get k8s pod auto-scaling without consequences? Or even manual scale down without manually removing nodes from the cluster? 

I just faced with the exact same problem, scale down from 5 to 3 instances and get 
`can't register client due to reason not_ready` 
I see 3 nodes running and 2 nodes running false with `vmq-admin cluster show` 
Exactly the same case as described.

Manual scaling and add/remove nodes from a cluster is not realistic in production or high in most use cases. Just curious do you guys have any advice here?
 
Is there a way to set `allow_multiple_sessions` and `trade_consistency` via env var in docker image ? 

Thanks!

**Comment by ioolkos** [comment]
@nmarcetic thanks...
1. If you want to be able to allow registers in a netsplit you have to allow for it: https://docs.vernemq.com/clustering/netsplits Set the `allow_register_during_netsplit = on` in VerneMQ config, and also see about the other allow values there.
The config values you mention (allow_multiple_sessions and trade_consistency) are obsolete, don't use them.

2. The idea is not that you manually make the nodes leave. The pod termination should automatically make the node leave, I think. Don't know what you did and why it didn't work. Maybe related: https://github.com/vernemq/docker-vernemq/pull/193

3. A VerneMQ cluster is stateful and membership is part of state. Verne doesn't just forget a node, because it was killed. That's why there's the `leave` command to tell the cluster. See point 2.

**Comment by nmarcetic** [comment]
@ioolkos Thanks for a prompt response. 

I see now, I will try right now with `DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT=on`.

**Comment by nmarcetic** [comment]
@ioolkos Looks same :disappointed: 

Running replica=5 

```
+-----------------------------------------------------------------+-------+                                                                                                                                        
|                              Node                               |Running|                                                                                                                                        
+-----------------------------------------------------------------+-------+                                                                                                                                        
|VerneMQ@mfx-adapter-mqtt-0.mfx-adapter-mqtt.mfx.svc.cluster.local| true  |                                                                                                                                        
|VerneMQ@mfx-adapter-mqtt-1.mfx-adapter-mqtt.mfx.svc.cluster.local| true  |                                                                                                                                        
|VerneMQ@mfx-adapter-mqtt-2.mfx-adapter-mqtt.mfx.svc.cluster.local| true  |                                                                                                                                        
|VerneMQ@mfx-adapter-mqtt-3.mfx-adapter-mqtt.mfx.svc.cluster.local| true  |                                                                                                                                        
|VerneMQ@mfx-adapter-mqtt-4.mfx-adapter-mqtt.mfx.svc.cluster.local| true  |                                                                                                                                        
+-----------------------------------------------------------------+-------+                    
```
Scaling down to replica=3
```
+-----------------------------------------------------------------+-------+
|                              Node                               |Running|
+-----------------------------------------------------------------+-------+
|VerneMQ@mfx-adapter-mqtt-0.mfx-adapter-mqtt.mfx.svc.cluster.local| true  |
|VerneMQ@mfx-adapter-mqtt-1.mfx-adapter-mqtt.mfx.svc.cluster.local| true  |
|VerneMQ@mfx-adapter-mqtt-2.mfx-adapter-mqtt.mfx.svc.cluster.local| true  |
|VerneMQ@mfx-adapter-mqtt-3.mfx-adapter-mqtt.mfx.svc.cluster.local| false |
|VerneMQ@mfx-adapter-mqtt-4.mfx-adapter-mqtt.mfx.svc.cluster.local| false |
+-----------------------------------------------------------------+-------+

```
All pods have `DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT:  on` set as an env variable. What I am missing?

**Comment by ioolkos** [comment]
Looks like you're mixing up two things: you now have a netsplitted cluster, but other than before you still can register clients! this is what you configured for with ALLOW_REGISTER. Normally, you could restart those 2 missing nodes, and then the netsplit will heal.

Your other completely unrelated issue is that you want to make those 2 nodes leave in Kubernetes. I do not know why this doesn't work as expected in your case. How do you actually scale down?

**Comment by nmarcetic** [comment]
@ioolkos Ah I see, still running nodes will now accept requests, got it now  ;) 
Ok testing now.

I scaled replicaset like this 
` kubectl scale statefulset mfx-adapter-mqtt  --replicas=5 --namespace mfx `
