### ISSUE TITLE
verneMQ with loadbalancer

### ISSUE THREAD

**Issue by odx-tech** [erlio/vernemq#365]
Hi,

We've setup VerneMQ on couple of nodes where in an android client connects to one of them and sends in geospatial data periodically. All the clients use different client-ids to connect to any one of the node and publish data to a common topic to which we have attached web-hooks to consume the data. The clients are sending qos-0 messages. There are no special subscribers for the data. 

What we are looking if this setup can be behind a load-balancer so that it is easy to add more nodes of vernemq when needed and client and is agnostic of the same. One problem I figured out with a load-balancer like ELB is that there is no client-id level session persistence and there could be scenarios where client registered on one instance can attempt to publish data on another instance because of this. Was wondering if there is a way to mitigate this out. 

Thanks,
Karthik

**Comment by ioolkos** [comment]
Hi @odx-tech cool to hear from you... :)
The question is rather general, in the sense of sticky sessions with a load balancer? do I paraphrase this correctly?

If yes, this is certainly possible with your load balancer of choice (HAProxy and the like). For ELB i wouldn't really know, I'm no expert there.
Let me know if I get your question wrong.

**Comment by odx-tech** [comment]
Hi @ioolkos 

My question is other way around. Given that ELB does not have sticky session for TCP and that kind of becomes a requirement for using vernemq(from what I've read) behind a loadbalancer for the reason I stated in the issue of client to be registered and data to be published to the same node, is it possible to circumvent this. 


Thanks,
Karthik

**Comment by ioolkos** [comment]
OK, so you have lots of mobile clients that periodically connect and publish, but don't subscribe to any topic.
I don't think you have persisted sessions (queues) there, so one of the main points for sticky sessions is already mitigated, that is to avoid queue migration from one VerneMQ node to another.

Did you try without that and actually run into practical problems?

Of course, you might still need sticky behaviour for some reason I don't know. In that case, I don't know what possibilites ELB offers to load balance mobile clients in a sticky way, apparently none?

**Comment by odx-tech** [comment]
The problems are obvious given a load balancer like ELB can push different requests to different nodes from a same client.  

Is there a way a client connected to say Node 1 can publish to a different Node 2 ? And lets say there is some sort of communication between Node 1 and Node 2.

**Comment by ioolkos** [comment]
Hi @odx-tech 

MQTT clients cannot directly control cluster communication, that is there is no way for a client connected to node 1 to somehow enforce delivery of the message on node 2.
For MQTT subscriptions this is handled automatically. The cluster knows where each message has to go.

You seem to deliver message via webhooks to a backend application, so there are no MQTT subscriptions.
This means that messages are basically dropped anyway on a MQTT level.

I might still misunderstand your architecture, but I think I have no immediate solution to the load balancer problem.

**Comment by odx-tech** [comment]
Hi @ioolkos,

I was not looking at MQTT clients to enforce cluster communication, but was wondering if behind the scenes via the normal cluster communication if clients registered on one Node could also get registered on the other. 



Thanks,
Karthik

**Comment by dergraf** [comment]
@odx-tech As far as I know ELB acts either as TCP or HTTP loadbalancer. For MQTT/VerneMQ a TCP loadbalancer is required, as Websockets is over HTTP/TCP the TCP loadbalancer MUST work per definition too. 

The way TCP loadbalancers work is that they keep a connection to the upstream server open as long as the client doesn't close the connection, until a connection error, or until a timeout (duration the LB keeps the connection open where no data is flowing in either direction). 

As a result for VerneMQ the MQTT session is alive as long the client keeps the connection open (unless error or timeout ofc). If the client gets disconnected it just reestablish (by reconnecting) the MQTT session (client previously used cleansession=false flag). In this case the LB could use a different upstream server, a VerneMQ cluster will automagically migrate the internal state stored on the 'old' node to the other node.

To reference your original message: "..there could be scenarios where client registered on one instance can attempt to publish data on another instance because of this" This IS NOT possible with a TCP based loadbalancer. If this is happening you're using an IP based loadbalancer, which ELB is not. 

I would check that VerneMQ clustering is properly configured and working, and then reconfigure ELB. Multiple of our users run VerneMQ behind ELB and it just works 

Hope this helps.

**Comment by odx-tech** [comment]
Hi @dergraf 

Thanks for the detailed answer. Is VerneMQ clustering needed for my use-case ?

**Comment by dergraf** [comment]
I don't know your exact use case.

You usually require clustering if you want to scale the number of clients and/or reach high availability.
If you don't require above clustering can be just for convenience as your publishers don't require to know on which node a matching subscriber is located. But in this case your scenario could well live with just a single MQTT server. 

Hope this makes sense.

**Comment by odx-tech** [comment]
Yes, so we do not have the subscriber problem. Our subscription is via web-hooks if you can say so. 

We'll need more nodes as and when scale increases but they are independent of each other.

**Comment by dergraf** [comment]
Closing. Please feel free to reopen.

**Comment by dhruvppatel** [comment]
@dergraf We are connecting to the vernemq cluster(docker vernemq/vernemq:1.10.4.1) from the browser using WebSockets for subscribing and reading data from selected topics. We have a front-facing alb that connects to the ec2 target groups(nodes of vernemq cluster)
Do we need to enable sticky sessions?

```
"message"  :  "15:52:44.940 [error] CRASH REPORT Process <0.14178.429> with 0 neighbours crashed with reason: no try clause matching {shutdown,{state,<<>>,vmq_mqtt_fsm,terminated,mqttws,#Port<0.2760025>,{{10,155,7,84},5132},{{1608,393164,488328},0},{{1608,393164,488329},0}}} in cowboy_websocket:handler_call/6 line 469" ,
```

We do see the above messages in the console.

**Comment by ioolkos** [comment]
@dhruvppatel thanks... it seems that you do not describe any faulty behaviour. Are you just wondering about the log, or do you actually see any faulty behaviour? 
I can investigate the error if needed, but I think it's a harmless termination (which admittedly then should not log an error).

[quick aside note: if you use our packages, please read the EULA].

**Comment by dhruvppatel** [comment]
@ioolkos We see a lot of these errors. Also, the count of connected clients in the grafana dashboard and alb doesn't match. it seems that the connected client counts in the grafana dashboard remain higher. 

We wanted to verify our VerneMq cluster setup for WebSockets. We are deploying the VerneMq cluster in Kubernetes using helm charts. We use the Paho client library on the browser side to connect to the VerneMq. Do we have any reference or recommendation page for the setup. for ex: Do we need to use a sticky session at ALB? Do we need to only allow `/mqtt` path? What should be timeout settings at ALB and VerneMQ config level?

**Comment by angeloskaltsikis** [comment]
Hello @dhruvppatel ,
Possibly the reason you see difference on the number of connected client counts vs what you see in the ALB is due to this [issue](https://github.com/vernemq/vernemq/issues/1466)

On the load-balancer part:
In our case we are using NLB (which supposedly has sticky sessions as well) but after running a quick experiment (connecting/disconnecting the same client with stable IP) it seemed that there was a big chance of the client ending on a different node.
I was able to locate the node that the client ended up with the following command
```
vmq-admin session show --node --is_online --client_id=<client_id>
```
We are also interested in making a "smarter" load-balancing scheme which will redirect same clients to same nodes (if the node is available) but it seems this can not be done with managed LB but can be done with an NGINX and some custom logic.
Please let me know if you make any progress with that.
