### ISSUE TITLE
vmq trace timestamp

### ISSUE THREAD

**Issue by VincentNgai86** [erlio/vernemq#398]
We are working in  vmq-admin trace client debug
however the out put record wuthout timestamp like this 

<7273.7847.487> MQTT RECV: CID: "XXX" PINGREQ()
<7273.7847.487> MQTT SEND: CID: "XXX" PINGRESP()

Would like to know if it is possible to add timestamp like

yyyyMMddhhmmss  <7273.7847.487> MQTT RECV: CID: "XXX" PINGREQ()
yyyyMMddhhmmss <7273.7847.487> MQTT SEND: CID: "XXX" PINGRESP()

**Comment by ioolkos** [comment]
It probably is. Tracing champ @larshesel speaketh your opinion!

**Comment by VincentNgai** [comment]
Hi @ioolkos 
I finally make it work with use another way 

apt-get install moreutils 
vmq-admin trace client client-id=xxxxx | ts '[%Y-%m-%d %H:%M:%S]']

But thanks for the followup

**Comment by larshesel** [comment]
Hi @VincentNgai86 - there is no way currently to add timestamps directly and I would have suggested exactly the solution you came up with. Btw. it was an explicit decision to not add timestamps as if they'd been added the format also had to be made configurable and since tools like `ts` exists I decided to keep it simple.
