### ISSUE TITLE
Memory keep increasing, slowly.

### ISSUE THREAD

**Issue by siscia** [erlio/vernemq#423]
### Environment

- VerneMQ Version: vernemq_1.0.1-1_amd64
- OS: Ubuntu EC2

Single instance on AWS EC2

### Expected behavior

Memory should be constant

### Actual behaviour

I have a pretty stable deploy of Vernemq.

A stable number of producer, a stable number of consumer and a stable number of messages.

However, I notice that memory, slowly but surely, keep increasing.

This is what caused my previous issues: #410 

It it normal?

**Comment by ioolkos** [comment]
Thanks for asking, @siscia!
Can I ask how much memory we're talking here in total?
Last time seems it was an out of memory situation. So maybe you're headed there again. Do you have any plugins active? 
I guess you don't have new insights about https://github.com/erlio/vernemq/issues/410

**Comment by siscia** [comment]
@ioolkos , we are talking about something really trivial.

```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:           486M        337M        7.4M        5.6M        141M        109M
$ free
              total        used        free      shared  buff/cache   available
Mem:         498380      345416        7560        5688      145404      111724

```

```
$ top
top - 14:06:41 up 42 days, 37 min,  2 users,  load average: 0.00, 0.00, 0.00
Tasks: 128 total,   1 running, 127 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :   498380 total,     7036 free,   345684 used,   145660 buff/cache
KiB Swap:        0 total,        0 free,        0 used.   111448 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                            
10355 vernemq   20   0 3875876 268420   1696 S  0.0 53.9  19:39.45 beam.smp                                                                           
```

How you can see now, the memory used by verne is roughly 54%, when I start to monitor it, 2/3 days back it was 49%.

(It actually slowly increased over time, it wasn't just an internal change in the machine or something...)

Yes, what I am afraid is to run out of memory again.
Now the system should be able to recover by itself, but still...

This is the config file running:

```
allow_anonymous = off
vmq_passwd.password_file = /etc/vernemq/vmq.passwd
listener.tcp.default = 0.0.0.0:1883
listener.ws.default = 0.0.0.0:8883

# log.syslog = on
#plugins.vmq_acl = off
#listener.max_connections = 10000
#listener.nr_of_acceptors = 10
#listener.mountpoint = off
```

And here the vm.args:

```
$ cat vm.args 
+P 256000
-env ERL_MAX_ETS_TABLES 256000
-env ERL_CRASH_DUMP /erl_crash.dump
-env ERL_FULLSWEEP_AFTER 0
-env ERL_MAX_PORTS 65536
+A 64
-setcookie vmq
-name VerneMQ@127.0.0.1
+K true
+W w
-smp enable
+zdbbl 32768
```

Other than the standard plugin for the authentication I don't have anything else running...

**Comment by ioolkos** [comment]
Ok, thanks! is that an Arduino or sth similar?
I think we have seen some memory fragmentation issues with devices like that.

**Comment by siscia** [comment]
No it is the smallest instance in AWS EC2.

**Comment by ioolkos** [comment]
Ok, trying to think more about it. Weather still ETOOHOT though...

**Comment by siscia** [comment]
What is ETOOHOT ?

**Comment by larshesel** [comment]
Just a geeky joke on posix error codes - he just means it's too hot to think :)

**Comment by larshesel** [comment]
Do your clients use fixed or random client-ids when connecting to the server? If not that might account for the increase in memory as each client-id will use resources on the server. Otherwise what you may be running into is memory fragmentation as @ioolkos suggested. Erlang allocates blocks of memory as needed and may not release the memory even if it is no longer in use - that depends on which memory allocator is used. So that the memory increases may not be a sign that there's a leak, but could just be because Erlang needed some more memory at peak time and hasn't decided to release it yet. I don't think an increase from 49% to 54% on a machine with only half a gigabyte of memory can be clearly classified as a memory leak - after all it accounts for about 25megabytes... 

It would be interesting to know what kind of load you're running on the server, are you using retained messages, offline messages etc.

**Comment by siscia** [comment]
My clients use random client-ids.

However the number of clients is fixed and stable, maybe a client can disconnect, and then reconnect with another id, but after a while, I guess that the old clients should be garbage collected.

The memory keeps increasing, now it is 56%. I don't think neither is a memory leak (or at least not a bad one for sure) or you would have noticed it already.

I am retaining something like 4 messages, no offline messages, nothing weird at all.
I am using Verne as MQTT backbone for a IoT project based on: https://docs.loraserver.io/overview/

**Comment by larshesel** [comment]
Old client-ids are not garbage collected (this is a technical detail due to the distributed nature of VerneMQ - a limitation that can be overcome at some point) so this could be what you're seeing. It is recommended (I don't think we've documented this explicitly) to restrict client-ids so to a fixed set - usually restricting them to be the same as the username is a good way to go.

**Comment by larshesel** [comment]
From an MQTT perspective it's also a good idea to not allow arbitrary client-ids, since if this is not restricted somehow one can in principle take over the session (forcing a disconnect of the already connected client) and authorization level of another client . So it's a security issue as well.

**Comment by siscia** [comment]
It is a security issue also if I have authentication in place?

**Comment by larshesel** [comment]
it may be ok - it depends on how authentication and authorization works in the particular place and especially if the authorization rules are derived based on the username or the client-id. It's just something one should think carefully about and in any case a malicious client authenticated client can force another client to be disconnected as long as it can guess the client-id of another client (this is a property of the MQTT spec). Also, since each new client-id takes up resources that are not being freed, a malicious authenticated client can reconnect continuously with new client-ids, thus using more and more resources on the broker.

**Comment by siscia** [comment]
But there is a way to clean up the old clientId ?

My use case -- I believe -- is acceptable, and I would like to avoid to restart the MQTT server every month...

**Comment by larshesel** [comment]
No, currently there isn't really a 100% way to do it. But all this said and discussed we haven't really found out if this is really the root cause for your OOM problem - it's just a likely candidate. But until we get around to completely deleting old client data (which is non-trivial in a distributed system) this is likely going to cause issues for you down the road if you keep using random client ids (as well as the other issues random client ids causes).

Note, restarting the broker is not enough to fix the client-id resources issue  as the client meta information is written to disk and reloaded when the broker is restarted.

But again - it is not clear this is really the problem you're having - looking at the memory usage report above you're running on a system with (in general) very little memory available no matter if VerneMQ is using 47% or 54% of memory and this means any spikes in traffic (causing memory usage to momentarily spike) may cause an OOM. As mentioned by @ioolkos you might run into memory fragmentation which is even more likely when so little memory is available and this can cause a process to be stopped. Memory fragmentation issues occur when a process asks for a chunk of memory, but there are no memory chunks available of that size, only smaller fragments and the memory allocator gives up trying to move stuff around to satisfy the request and the calling process is terminated.

Sorry for not being of more concrete help here.

**Comment by siscia** [comment]
Are there any way to verify either options?

Can I request the number of clients that vernenq thinks are connected? If the problem is the random clientsId this number should be quite high, correct?

----- Messaggio originale -----
Da: "Lars Hesel Christensen" <notifications@github.com>
Inviato: ‎26/‎06/‎2017 16:32
A: "erlio/vernemq" <vernemq@noreply.github.com>
Cc: "Simone Mosciatti" <sisciaprivate@gmail.com>; "Mention" <mention@noreply.github.com>
Oggetto: Re: [erlio/vernemq] Memory keep increasing, slowly. (#423)

No, currently there isn't really a 100% way to do it. But all this said and discussed we haven't really found out if this is really the root cause for your OOM problem - it's just a likely candidate. But until we get around to completely deleting old client data (which is non-trivial in a distributed system) this is likely going to cause issues for you down the road if you keep using random client ids (as well as the other issues random client ids causes).
Note, restarting the broker is not enough to fix the client-id resources issue as the client meta information is written to disk and reloaded when the broker is restarted.
But again - it is not clear this is really the problem you're having - looking at the memory usage report above you're running on a system with (in general) very little memory available no matter if VerneMQ is using 47% or 54% of memory and this means any spikes in traffic (causing memory usage to momentarily spike) may cause an OOM. As mentioned by @ioolkos you might run into memory fragmentation which is even more likely when so little memory is available and this can cause a process to be stopped. Memory fragmentation issues occur when a process asks for a chunk of memory, but there are no memory chunks available of that size, only smaller fragments and the memory allocator gives up trying to move stuff around to satisfy the request and the calling process is terminated.
Sorry for not being of more concrete help here.

**Comment by larshesel** [comment]
The number of active connections can be shown by subtracting `counter.socket_open - counter.socket.close` which in the above case means 5 clients are currently connected. The memory usage of client-ids no longer used is not available directly using the command line tools.

**Comment by saranglakare** [comment]
I am facing a similar issue and now unable to run vernemq on our 4GB box as it goes out of memory and crashes (single instance - no cluster). We have less than 2000 active connections. However, we may have older clients that have disconnected and never gotten back.

I have 2 questions:

1. Is there a way to know the count of unused client-ids?

2. Is there a way to delete all data belonging to the unused client-ids?

What is the way out for us? Can I delete all data and restart? If so, how?

Thanks!
