### ISSUE TITLE
TLS Based Authentication

### ISSUE THREAD

**Issue by vedavidhbudimuri** [erlio/vernemq#446]
### Environment

- VerneMQ Version: 1.1.0
- OS: Ubuntu 16.04
- Erlang/OTP version (if building from source): 20

Unable to authenticate user in tls based authentication. 
`
2017-07-16 13:09:09.233 [warning] <0.4921.0>@vmq_mqtt_fsm:check_user:546 can't authenticate client {[],<<"client_1">>} due to chain_exhausted
`

Generated certificates using openssl

**Comment by vedavidhbudimuri** [comment]
Here is my config fine, Im sure that im using file based authentication as i check with out passing the certificates to 1883 port. 
[vernemq.txt](https://github.com/erlio/vernemq/files/1151100/vernemq.txt)

**Comment by larshesel** [comment]
Your configuration looks fine - are you passing the proper username and password when creating the TLS connection? Both the username and password has to be passed and there has to be an entry for the user in the `vmq_passwd` password file, otherwise the `vmq_passwd` plugin will 'give' up and let the next plugin in the chain handle authentication - but if there are no more plugins you'll see the `chain_exhausted` and the client will be rejected.

**Comment by vedavidhbudimuri** [comment]
Hey @larshesel,
Yeah I'm passing valid username and password, as I was able to connection to broker, publish and receive messages on 1883 port.

**Comment by larshesel** [comment]
can you do `vmq-admin trace client client-id=client_1` and try to connect with the client again (using client-id `client_1`) and post the output here?

**Comment by vedavidhbudimuri** [comment]
Im unable to reproduce the issue now, Thank you very much for your support. One more clarification      
as im setting listener.ssl.use_identity_as_username = on, its no longer necessary for me to send the username and password right?

**Comment by larshesel** [comment]
If you do the username will be overwritten with the client certificate common name - if you want to use `vmq_passwd` you still have to pass in the password, otherwise the plugin will be skipped and authentication rejected.

**Comment by vedavidhbudimuri** [comment]
Thank very much @larshesel.
