### ISSUE TITLE
clients not reflected in vmq-admin session show / trace client

### ISSUE THREAD

**Issue by syberkitten** [erlio/vernemq#464]
clients using https://github.com/emqtt/CocoaMQTT

having many issues with the broker:

- I'm not able to see them via "vmq-admin session show" - even though they claim to be connected.
- retained messages take more then 60 seconds to arrive.

They seem to be lost in the stratosphere. :(

**Comment by dergraf** [comment]
@syberkitten please be more specific when opening issues... otherwise it is very difficult to keep up for us.

If you're not seeing any error in `console.log` when running `vmq-admin session show` your clients aren't (yet) connected from VerneMQ perspective.
1. Check the logs that you're not running in authentication issues
2. Check the logs that we don't log any weird parser errors.
3. Check your client software. We recommend to use `moquitto_sub`/`mosquitto_pub` to verify that it works with the those 'semi-official' mosquitto tools
3.a) if it works with mosquitto tools, it's likely a bug in the other client (we've seen this multiple times before, report the issue on their issue tracker)
3.b) if it doesn't work with mosquitto tools, please open an issue here.

Retained messages are delivered right after a matching subscription is inserted, although this could take some time in a clustered environment, it won't take 60 seconds, otherwise you're screwed... and should see a lot of other issues with clustering.

And yeah Stratosphere is probably a bit too far away.. my guess is they are one or max two network buffers away. I'd recommend to ALWAYS use Wireshark when debugging connection issues on that level.

**Comment by syberkitten** [comment]
@dergraf 
Thanks for the guidelines, first I don't have Auth working yet,
and I also don't have the clustering yet, so the setup is very basic.

The complaints came from an offshore team, that was working on IOS
giving me information that they are connected and the proper client Id,
but it was not reflected via the ```vmq-admin trace client client-id=``` command.

hopefully I'll be able to bring more data once we try this again,
I've switched to a different broker so teams can work. (for now)

**Comment by syberkitten** [comment]
@dergraf 
What happens is that sometimes the command gets a timeout:

```/vmq-admin session show
RPC to 'local@127.0.0.1' failed: timeout
```

Our use case is Such:
- client connects to the broker
- client sends one message
- client subscribes to 6000 topics in total (iterating 2000 clientID's), in this fashion:
     subscribe to:
       -/clientID/a
       -/clientID/b
       -/clientID/c
- client should receive all retained messages if there are (for each an every one of the 2000)
My team reports the following with VMQ,
lets say the subscription order is thus:
A1 A2 A3 B1 B2 B3 

The responses come as such:
```
Subscribed A1
Subscribed B1
Subscribed C1
30s - 1min lagg
Subscribed A2
Subscribed A3
30s - 1min lagg
Subscribed B2
Subscribed B3
30s - 1min lagg
Subscribed C2
Subscribed C3
30s - 1min lagg
Receiving message from B1, B2, B3
```

We also tested other brokers and we get a different order and no Lag (EMQ):
```
Subscribed A1
Subscribed A2
Subscribed A3
Subscribed B1
Receiving message from B1
Subscribed B2
Receiving message from B2
Subscribed B3
Receiving message from B3
Subscribed C1
Subscribed C2
Subscribed C3
```
Summary:
1) Subscription confirmation does not go in order of subscriptions as in EMQ. 
2) Confirmations go in batches - after each batch there is a about 1min of lag and then new batch of confirmations arrive
3) Messages does not arrive immediately after i got subscription confirmation

**Comment by ioolkos** [comment]
SUBSCRIBE overload. Is the client able to do the subscribes at a certain rate? (just as a test).
Let's say 1000 subscribes per second, instead of 6000 per millisecond or something ;)

Do we have an explanation for the 30 seconds pattern?

Also, it might be worth to optimise the topics (whole topic tree). Each client needs to know 2k Client IDs here? (I don't have the whole picture, of course).

**Comment by syberkitten** [comment]
@ioolkos 
Well, probably an issue of (as i understood from @dergraf ) having the message
queue non responsive since we were subscribing to 6000 topics one by one
via our IOS app.

Once the subscription is finished session show becomes responsive again,
and we are currently in process of using a different library for IOS which allows
bulk subscribe, so hopefully this will be resolved.

**Comment by larshesel** [comment]
The original issue (the title of this issue) about the session show not displaying the connected clients, could this not be due to the limit where only 100 results are shown per default? This is a mechanism to protect vernemq (and the caller) from having to handle potentially millions of results.
