### ISSUE TITLE
Question about the memory usage

### ISSUE THREAD

**Issue by edwinAtWiz** [erlio/vernemq#511]
### Environment

- VerneMQ Version: latest build from master
- OS: 16.04
- Erlang/OTP version (if building from source): 20

I've setup a cluster with 3 nodes, and publish a bunch of message to the cluster with **different client id**. Memory grows constantly as expected and mentioned in #423 . 

After that I tried to set the persistent_client_expiration to 1h and leveldb.maximum_memory.percent to 30, but it seems that the memory usage still at a high percentage and exceed the limit after 2 hours later. 

So i wonder if these two params could limit the memory usage resolved for the random client id. If not, is there anything we can do to garbage collected the old client that It never reconnect back after a period ? Thanks.

**Comment by larshesel** [comment]
Unfortunately not.

As is, every new client id will stay around forever. The problem boils down to doing real distributed deletes which is a hard problem to solve, since when you delete something you no longer have a causal context and deletes can therefore reappear. The solution we're using at the moment is to mark a client-id as deleted by setting the value of to a special tombstone value but keep the key (the client-id) around and keep the causal context. This way deletes work, but we pay for it in terms of resources.

We do have some plans to experiment with other causal frameworks supporting actual deletes, but this is in the early stages and even a prototype likely won't be around for quite a while yet.

**Comment by edwinAtWiz** [comment]
@larshesel  Thanks for your reply. But the performance will be quickly reach the bottleneck because of the high memory consumption. I've tried to restart the node one by one but some issues occurred:
 - sometimes the node keep 100% cpu usage and won't drop
 - take a very long time to get ready (if not ready, exception will be thrown when i type `vmq-admin cluster show`)
So at the moment, any way to mitigate the issue?

**Comment by larshesel** [comment]
The 100% cpu usage is because the node is reading back all the old metadata (client information) from disk and rebuilding the hash/merkle-trees used to be able to synchronize and replicate data between nodes. This metadata includes all client-ids that have ever connected so this can take a while. You have to plan for this time and wait for the cpu usage to fall down before using the node.

**Comment by larshesel** [comment]
I should add, that as retained messages are also fully replicated each topic with a retained message is subject to the same restrictions as client-ids, namely only 'tombstone' deletes exists as described above. In other words, for any topic with a retained message, a key/value pair of topic/tombstone will stay around forever, even after the retained message was deleted as per MQTT spec.

**Comment by originsmike** [comment]
@larshesel so if I publish several retained messages to the same topic, are they all saved forever, or only the most recent message sent to that topic? If they're all saved, that means retained messages can't be used with VerneMQ.

I'm seeing steady unbounded RAM growth in a single node cluster with ~500 clients, about 1 message per minute per client, even after setting LevelDB to a max of 10%. After 24 hours, VerneMQ exceeds 1GB of memory. Memory usage isn't proportional to the number of clients though, so it's not a TCP buffers thing. Still going through past memory leak issues and trying to figure out if I should file a new one.

**Comment by larshesel** [comment]
Only the most recent retain message is saved for a topic.

**Comment by jnicholls** [comment]
I too am seeing one particular node with steady memory growth, and another node with stable/low memory (cluster size of 2). I have an even distribution of client sessions between the two nodes, but the one node with high memory use has a particular client that is subscribed to a topic upon which the other client sessions are publishing about once per second. So my theory is that this steady growth has to do with clients that are subscribed to a busy topic.

Some more information:
* all client ids are unique; there are 8 clients in total: 7 producers and 1 consumer.
* node 0 is using 70MB, node 1 is using 1GB.
* the consumer client is connected as a persistent session, so that it can go offline and messages can queue up for its subscriptions to be delivered when it comes online again.
* all messages are QoS 1 both publish and subscribe.
* no retained messages being used, but the 7 producers have a LWT message.
* Node 1's primary (well, only) memory hog is from the Erlang runtime `beam.smp`. This suggests that some data is not being released as it should due to some reference lying around.

I don't understand why the memory grows to this level and never lets go of it. And only on the node where there is a subscribed consumer of many messages. I'll keep an eye on it to see if its resident memory continues to go up over the next 24 hours.

**Comment by jnicholls** [comment]
I just read through #591 which makes me think this is directly related to LevelDB and my subscriber's persistent session. I will have to try a setup where I am explicitly limiting LevelDB's `write_buffer_size` and `maximum_memory` as a byte value to see if this contains the growth.

**Comment by dergraf** [comment]
@jnicholls the default value for `leveldb.maximum_memory.percent` is 70 which we learned is for a lot of deployments too high... Using this, you'll see VerneMQ eating memory up to around 70% of the system memory. 
We still have to come up with a good default value, but in many situations 20-30% is more than enough to run smoothly.

**Comment by jnicholls** [comment]
@dergraf It sounds like despite that value, memory will grow due to the `write_buffer_size` and that an explicit `write_buffer_size` + `maximum_memory` in bytes is the ideal way to go. But perhaps for default's sake, changing the default `maximum_memory.percent` to 20 or 30 and also supplying a default `write_buffer_size_min` and `write_buffer_size_max` makes sense for predictable memory consumption?

**Comment by saranglakare** [comment]
We are facing this exact same problem (ver 1.9.2) on a single 4GB box. 

Instead of closing this issue, can we give some steps to solve it? I am guessing this is a very common issue for products where new users come and go. There will be lot of client-ids that are never re-used and I am guessing they are adding up and making vernemq go out of memory.

I could not find how to 1. delete data of old client-ids so can run cleanup once in a while, 2. delete all data to start afresh.

Any pointers would be highly appreciated!

**Comment by ioolkos** [comment]
@saranglakare hi.. please do not attach to multiple closed issues, but open a new one.

- please review https://github.com/vernemq/vernemq/issues/591#issuecomment-360441621 on how to more tightly control LevelDB configs
- please switch to SWC metadata protocol

**Comment by saranglakare** [comment]
ok, thanks. I added comment here as it is the same issue I am facing. I tried the levelDB config given in #591 and it did not help. So I finally deleted all data and re-started VerneMQ.

About SWC, I read about it in #1410 and it seems to affect the disk usage. Does it also improve the memory usage?

Key question is: does vernemq have a solution for older client IDs now? I am quite certain that's the problem we faced.

PS: Should I open new issue for this ^?

**Comment by ioolkos** [comment]
What do you mean by "a solution for older ClientIDs"? Note that the issue is that LevelDB will store your clientIDs for quite a while before it can delete them, so historically the recommendation is to not create single-use ClientIDs. SWCs adresses that to some extent.

- yes, please open a new issue, if you want to keep discussing this.

**Comment by saranglakare** [comment]
> What do you mean by "a solution for older ClientIDs"
Client IDs of inactive users still using memory. After months of using VerneMQ, the memory usage grows and then crashes due to out of memory and even refuses to restart. @larshesel in the first reply mentioned "As is, every new client id will stay around forever." <- this is what I am referring to. 

> historically the recommendation is to not create single-use ClientIDs
We do not create "single use" IDs. However, it is common for users to start using the system and then go away (sometimes forever). If ID for these users and data is going to persist, then eventually VerneMQ server's capacity to serve will dwindle.

I do not want the old client IDs to be around forever. I want inactive IDs to be removed. Is this something handled by LevelDB or VerneMQ? Does SWCs address the removal (I have searched around a lot and these important questions are not answered anywhere).

**Comment by ioolkos** [comment]
@saranglakare SWC will help you with your issues. Please use at least release 1.10 for that. (note that the compiled packages for those are under a commercial EULA).
