### ISSUE TITLE
SSL/TLS Server and Client Authentication with Intermediate Certificates

### ISSUE THREAD

**Issue by tomcis** [erlio/vernemq#551]
Hello,

First of all, thank you for providing us with such an amazing open source software. I am writing here in order to ask some questions about authentication possibilities with VerneMQ. I have started implementing SSL Server side authentication and managed to authenticate server successfully when using only Root CA. However I have bumped into some authentication problems when changing the Root CA with Certificate Chain consisting of one Intermediate CA (signed by Root CA) and Root CA. Is it possible to authenticate server to a certificate chain with VerneMQ? If yes, is it also possible to authenticate clients to different certificate chains than servers (since clients would be certified by different intermediate CA)?

So the main idea once again is:
- Root CA can authenticate two Intermediate CAs which would authenticate clients and servers separately.
- During each connection between clients and servers/brokers they would have to authenticate each other to different CA chains (because of different Intermediate CAs).

I hope the explanation is clear. Thanks a lot in advance!

Certificate chains with intermediate CA explained: https://jamielinux.com/docs/openssl-certificate-authority/index.html

**Comment by ioolkos** [comment]
@tomcis thanks for your question!
I'll have to look into it; I apologise that I haven't found time yet. VerneMQ SSL capabilities are basically defined by what the underlying Erlang system's SSL capabilities are. Should VerneMQ support what you have described? is it standard procedure in other words?

**Comment by tomcis** [comment]
@ioolkos 
Thank you for your answer! I expect VerneMQ to support Certificate Chains since, as far as I see, it is implemented in Erlang by default (http://erlang.org/doc/man/ssl.html ; search depth), depth is set to 1 which means one Intermediate CA is allowed in the chain. However I did not manage to make it work yet. Also my other part of the question was: is it possible to define different Root or Intermediate CA (different than server) to authenticate clients in the server/broker?  I assume now both server and client are authenticated to the same CA since there is only one CA-file option in the config (which is specifically related to the server):

`listener.ssl.cafile = /etc/ssl/cacerts.pem`

and everything what can be found concerning client authentication is this:

`listener.ssl.require_certificate = on`

**Comment by larshesel** [comment]
Hi @tomcis 

VerneMQ should support intermediate CAs with no problem. There's also a (hidden) option to set the depth on a listener with `listener.ssl.depth = 3` (see https://github.com/erlio/vmq_server/pull/114).

I'm not sure I understand the second part of the question?

**Comment by tomcis** [comment]
Thank you very much for you reply @larshesel 

Sorry for my late reply - in the meantime, I have been trying many different configurations of interemediate certificates (https://jamielinux.com/docs/openssl-certificate-authority/index.html). Finally, I have managed to make an intermediate certificate work once (by the way, it also worked without changing the depth since I use only one IntermediateCA and `listener.ssl.depth` is by default equal to 1). However my problem still persists since I cannot reproduce my results (chain configuration) again and make it work with an intermediate certificate.

What is interesting though, is all kinds of configuration of CA-Chain worked for a different broker (namely, Mosquitto Broker - when trying to connect from an external Mosquitto client through SSL). It seems that VerneMQ is very picky on that and just rejects everything. Do you have any idea? Maybe Erlang is more strict on the Certificate Chain checking itself (maybe CN/FQDN for Root CA or Intermediate CA always has to match the same server, or any other constraint)? (using only Root CA without Intermediate CA to sign a server certificate always works for me though).

This is the result when I try to connect from a Mosquitto client to the VerneMQ broker (unfortunatelly, there is no extensive debugging mechanism). It gets into a halting state:

```
ubuntu@ip-172-31-29-239:~$ sudo mosquitto_pub -d --cafile ca-chain.cert.pem -h ec2-34-215-140-8.us-west-2.compute.amazonaws.com -t "test" -m "hello" -p 8883
Client mosqpub|1937-ip-172-31- sending CONNECT
```

Part #2
------

Sorry for my bad explanation.. I hope this image clarifies the wanted certificate architecture:

![capture](https://user-images.githubusercontent.com/7864776/33888149-7b1c0558-df4c-11e7-8ae1-45b356eddf2c.PNG)

I think this seems to be possible now by inputting CA-Chain #1 when sending a client connecion request to a broker, and defining CA-Chain #2 in the broker itself under the `listener.ssl.cafile`. However chains do not work for me yet (as described already before) thus I cannot test it yet..

Any help would be appreciated a lot!

**Comment by ioolkos** [comment]
Wow, thanks!

If you made it work once, then it should work in principle, right?
is it possible to use `openssl s_client` to see if any other errors come up?
Yes, Erlang TLS is super picky. (seen a lot of stuff, order, whitespace problems in certs, you name it). But I can't really judge the details here.

Maybe we should ask some Erlang folks for ideas?

**Comment by tomcis** [comment]
@ioolkos, thanks for all the support!

I have solved most of my problems already, thus I think it would be wise to share it with others since I, myself, have wasted too much time on that.

The certificate problems were basically related to the permissions of the folder where my private keys were in (namely, `private/` folder). I guess Mosquitto Broker might have different access rights than VerneMQ thus it was able to get the private key and run the SSL, however VerneMQ was always throwing a TLS error. Giving `execute` public rights for the folder made it work.

After solving certificate issues I have also managed to implement the above-mentioned architecture. In general, Erlang written brokers have a bit different SSL authentication structure, however, surprisingly, it allowed quite some freedom which made this architecture possible. 

Thanks for everyone, and at least for now - I think this can be closed.

**Comment by larshesel** [comment]
Wow, cool you found the problem! Let us know if you run into other issues!

**Comment by jnicholls** [comment]
Hi @tomcis and @larshesel. I'm having a similar issue with intermediate CA certificates. I too set the hidden config `listener.ssl.depth=2` but I am still receiving an `unknown ca` handshake error when my MQTT client sends its certificate. The interesting part is if I send the entire cert chain with the client cert request (using `openssl s_client`) then vernemq accepts the client certificate. It won't accept it when it's only the client certificate that's been signed by the intermediate CA. The server is configured with a `cafile` that is the intermediate CA + root CA certificate. The difference in my setup than with @tomcis's setup is that my intermediate CA has signed both the server cert and the client cert.

Hope you all have some tricks up your sleeves :) I think the behavior of my MQTT client (sending only the client cert and not the whole chain) is the correct and desired functionality. It just appears that Erlang is not verifying it against the provides `cafile` certs, even with an appropriate `depth` configured.

**Comment by dhaval1983** [comment]
I really have hard time working with Vernemq, I am on cpanel based server, and wss is somehow not working and throwing below error - attached is the config file, not sure what to do, tried a lot but still looking for a solution. can some one please help

[vernemq.txt](https://github.com/erlio/vernemq/files/2055656/vernemq.txt)
WebSocket connection to 'wss://dev.dollarexch.com:8443/mqtt' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID

**Comment by chouhan** [comment]
Hi @tomcis, @larshesel 

I have followed all the steps from the very beginning of this post. I wan't not able to succeed any further. I am exhausted trying various options to make VerneMQ broker work with Root & Intermediate Key pairs.

I have the same set of questions you had previously. I am again mentioning it here.

**Is it possible to authenticate server to a certificate chain with VerneMQ? If yes, is it also possible to authenticate clients to different certificate chains than servers (since clients would be certified by different intermediate CA)?**

So the main idea once again is:

- **Root CA can authenticate two Intermediate CAs which would authenticate clients and servers separately.**

- **During each connection between clients and servers/brokers they would have to authenticate each other to different CA chains (because of different Intermediate CAs).**

**Certificate chains with intermediate CA explained: https://jamielinux.com/docs/openssl-certificate-authority/index.html**

Here is the directory listing's of the certificates, that I created following the article from 

![image](https://user-images.githubusercontent.com/2761678/44008060-d76c1142-9e6c-11e8-9780-eeec33501d18.png)

_Just to avoid all permission issues, I created the below certificates in /root/ca folder and copied over to /home/osboxes/vmq-certs/_

Also for everything to look easy, I gave the same passwords to all certificates as "root"

Root private Key

![image](https://user-images.githubusercontent.com/2761678/44008157-2468f720-9e6e-11e8-8374-d291e1d513d4.png)

Root Certificate:

![image](https://user-images.githubusercontent.com/2761678/44008146-07710072-9e6e-11e8-90c0-f7bcea9c2809.png)

Directory Structure for Intermediate Certificates:

![image](https://user-images.githubusercontent.com/2761678/44008181-5e93b0e8-9e6e-11e8-8edd-63696b0b5abc.png)

Intermediate Keys:

![image](https://user-images.githubusercontent.com/2761678/44008242-21a3a976-9e6f-11e8-96c4-87b9ac5a8aa3.png)

Intermediate Certificates:

![image](https://user-images.githubusercontent.com/2761678/44008188-733264ae-9e6e-11e8-98ac-13f0a9a5af07.png)

As per the documentation from here

- Created server.cert.pem for VerneMQ broker
- Created client.cert.pem for connecting to VerneMQ broker via MQTT.fx UI client

Following the VerneMQ [documentation](https://vernemq.com/docs/configuration/file-auth.html#authentication), using the vmq-passwd tool I created a user "root" and password as "root"

Here are the values that I set in /etc/vernemq.conf

- allow_anonymous = off
- allow_multiple_sessions = on
- listener.ssl.default = 127.0.0.1:8883
- listener.ssl.cafile = /home/osboxes/vmq-certs/intermediate/certs/ca-chain.cert.pem
- listener.ssl.certfile = /home/osboxes/vmq-certs/intermediate/certs/server.cert.pem
- listener.ssl.keyfile = /home/osboxes/vmq-certs/intermediate/private/server.key.pem
- listener.ssl.require_certificate = on
- listener.ssl.tls_version = tlsv1.2
- plugins.vmq_passwd = on
- plugins.vmq_acl = on

Here is what I see from the MQTT.fx UI client, with root:root  "User Credentials tab"

![image](https://user-images.githubusercontent.com/2761678/44008395-2ee09b92-9e71-11e8-822f-72388b988acd.png)

Also, if I change the SSL/TLS option from "Self Signed Certificate" to "CA Certificate file".

![image](https://user-images.githubusercontent.com/2761678/44008693-27323c5e-9e74-11e8-979b-a263317220c1.png)

Also, here is the vmq.acl I have

![image](https://user-images.githubusercontent.com/2761678/44008944-53aa7844-9e76-11e8-82df-eb2b7da26329.png)

**What are the other possible options that I need to try to make this work?**
**Is that something to do with vmq.passwd, which is encrypted and the MQTT.fx client does not decrypt it properly with the root/intermediate certificate pairs? If that was the case, then why would it work for the below?**

However, I was able to make it work with 2 different ways following this git comment post https://github.com/emqtt/emqttd/issues/562#issuecomment-221500588

- With **CA Certificate file option in MQTT.fx client** and User Credentials (root:root) in MQTT.fx UI client.

![image](https://user-images.githubusercontent.com/2761678/44008854-b47f0afa-9e75-11e8-8db3-1761815e925f.png)

- With **Self Signed Certificate option in MQTT.fx client** and User Credentials (root:root) in MQTT.fx UI client.

![image](https://user-images.githubusercontent.com/2761678/44008900-f7d3b576-9e75-11e8-9d3b-70d39ef1078b.png)


Really appreciate if I can get any suggestions/inputs or help on how to solve this with Root/Intermediate Certificates.

Let me know if I can provide you with more details you may need from me.

Thanks,
Rakesh

**Comment by egimbernat** [comment]
Well, this will be a long post, but the intention is to show a solution for the Self Signed SSL integration.

I think this topic is worth a chapter on VerneMQ Documentation. Any MQTT server that has the architecture need of being exposed to the internet must be protected with TLS. @ioolkos @larshesel I can help with that if you need :)

To get the things easy going and to explore more in detail the CA chain of trust certificate implementation, I created a simple repo that contains a Bash executable for creating sample certificates, including Server and Client ones. It was tested with VerneMQ, Mosquitto clients and MQTT.fx. It can be found here: https://github.com/egimbernat/quick-ca

The recommended VerneMQ configuration is:

```
listener.ssl.cafile = /etc/vernemq/ssl/ca-cert.pem
listener.ssl.certfile = /etc/vernemq/ssl/server-cert.pem
listener.ssl.keyfile = /etc/vernemq/ssl/server-key.pem


listener.ssl.depth = 2
listener.ssl.require_certificate = on
```
You may want to adjust the parameters.

**The CA certificate MUST no be your CA root, should be the CA Root + Intermediate certificate, aka chain of trust concatenation**

### Short explanation: 
Using CA and Intermediate certificates and using it for creating Server and Client certificates **IS TOTALLY POSSIBLE**. If https://jamielinux.com/docs/openssl-certificate-authority/introduction.html is used as the start point, they are two topics to be aware of:

- `-aes256` should not be present in Server certificate
- If the intention is to have thousands or even worse, millions of nodes connected to MQTT server is not the best choice an RSA length of 2048. For the most cases, is better to have shorter keys and renew it more frequently, but of course, is scenario dependent.

### More detailed explanation: 
Is not possible to use encrypted keys on Erlang, or at least, AES 256. [More info](https://stackoverflow.com/questions/50813212/erlang-ssl-password-option-for-private-key) 
When you set a password to SSL key you have to introduce it in most cases, every time the server restarts. That is, the password should leave somewhere in the environment or code, so at final, if your server gets compromised the attacker could get the password along with the private key. The things get even worse on orchestrations or cluster scenarios.

When it worth to have keys with a password? At the very first 2 steps of the trust (CA and root intermediate)

I really think that the dramatic or picky language here is Java, no Erlang ;)

**Comment by jnicholls** [comment]
I have figured that putting a TLS terminating proxy in front of VerneMQ to be not only a satisfactory solution, but an optimal one. Especially one with a more mature and regularly updated TLS stack.
