### ISSUE TITLE
Lua scripting docs don't mention it's critical to call http.body after making an http request

### ISSUE THREAD

**Issue by originsmike** [erlio/vernemq#588]
This is just a doc issue with [the lua scripting page](https://vernemq.com/docs/plugindevelopment/luaplugins.html#http-and-json-client-libraries). Just want to save the next person a few hours of debugging :)

I was tipped off by https://github.com/erlio/vernemq/issues/341 ; basically, if you make http requests without calling http.body on a non-false response, you're leaking some sort of HTTP sessions inside hackney. The tricky part is that when the sessions are exhausted, the error you see is connection_timeout, which it takes the full 8 seconds to report, so it looks like a genuine timeout. The timeout error also tears down the current client's MQTT session, along with any other sessions that are unfortunate enough to currently be waiting their turn to execute a hook.

Fixing the docs would help. A better fix would be to change the error message so it's not a red herring and tells you what you're doing wrong.

I don't call this a bug because golang's HTTP client library has the same failure mode. See https://github.com/golang/go/issues/17166

**Comment by ioolkos** [comment]
@originsmike thanks a lot for reporting!

not sure I understand it fully on first read, but no worries, we'll try to fix the doc. (cc @larshesel @dergraf )
We really appreciate your effort and letting us and future users know about it!  :thumbsup:

**Comment by larshesel** [comment]
HI @originsmike I took a look at how we handle the http connections using hackney and hackney will keep the connection from going back to the pool until the user has read everything it can using the reference returned from the request. So as you correctly found out, not calling the body function will lead to a complete exhaustion of the connection pool and everything grinds to a standstill and timeouts happen.

It's easy to document that one *must* call http.body. Changing the error is harder (as it comes from hackney). Another possibility is to tell hackney to return the actual body instead of a reference which could be later read (this would free up the connection immediately AFAICT) using the `with_body` option (https://github.com/benoitc/hackney/#read-the-body). Then users would not have to call http.body at all as it would be returned directly - however that would mean a breaking change to the lua interface.

I'm not sure what the right approach would be, but I'll for sure make an update to the docs for now.

**Comment by originsmike** [comment]
@larshesel could you use the `with_body` option and hang the response body off the returned response object, making `http.body` just extract the already-fetched response body? If garbage collection in Lua is smart enough, that wouldn't require an API change.

However, doing that would cause `http.post` to block until the response is completely read; if you wanted to preserve the current behavior, letting `http.body` block only if the body hasn't already been completely read, that's still doable but probably more trouble than it's worth.

**Comment by larshesel** [comment]
Yeah, I think just returning the body instead of the ref in the response and and let `http.body` return the body  might be an acceptable way to go. It feels a bit wrong as the http.body call becomes completely redundant. But I guess we could just deprecate it in the next minor version then and tell users to use the returned value directly (but code calling http.body would still work).

I think preserving the current behaviour isn't important and letting it block is fine. What do you think @dergraf ?

**Comment by originsmike** [comment]
Another idea: do you get any sort of callback in Erlang land when the Lua object returned from http.post goes out of scope or gets garbage collected? If so, you could surreptitiously retrieve the response body there if http.body was never called.

But I agree with you, that there's probably not a lot of code that depends on the current behavior of http.post (after all, these should be lightning-fast requests to local servers) so just deprecating http.body is simpler and probably fine.

**Comment by dergraf** [comment]
@larshesel, @originsmike I think we don't need to preserve the current behaviour. Letting it block is absolutely fine, especially as we don't have a 'sane' way to deal with concurrency inside the Lua script.

**Comment by larshesel** [comment]
Merged PR #802 with a fix so the connection is always released to the connection pool even if http.body isn't called. I also updated the note in the docs (just pushed the change, so it's likely still building). Thanks for pointing this out and sorry it took so long to do a proper fix.
