### ISSUE TITLE
Publishing a (retained) message to a given topic

### ISSUE THREAD

**Issue by testark** [erlio/vernemq#62]
I'm trying to write a custom plugin for VerneMQ. Everything is working fine (amazing product BTW), but now I'd like to be able to manually publish a (retained) message to a given topic as part of my plugin flow. Is there an API plugins can use to publish messages to topics?

**Comment by dergraf** [comment]
It is possible to publish and subscribe messages from plugins. However the fuctionality is currently quite limited, e.g for publishing you can only set topic and payload.. but it would be a great addition to pass some options to the publish call.

**Comment by testark** [comment]
@dergraf Yes, that would be great. Anyways, that could suit me. Can you point out how do I access the publish function from a plugin?

**Comment by dergraf** [comment]
the erlio/vmq_systree and erlio/vmq_bridge dependencies are using it. You can use this as an example. However, we haven't streamlined that API and it will probably change it soon as discussed above. Moreover we aren't happy with the way this API is exposed and still have to figure out a clean approach for it. For that reasons you also won't find any documentation for it.

```erlang
{RegisterFun, PublishFun, SubscribeFun} = vmq_reg:direct_plugin_exports(YOURPLUGINNAME)
```
which is essentially used here https://github.com/erlio/vmq_systree/blob/master/src/vmq_report_systree.erl#L44,L45 , although we used the indirection over the application environment in order to not have a compile time dependency to the ``vmq_reg`` module.

Those Funs can now be used in your plugin. The ```RegisterFun``` is typically only used if your plugin also receives messages e.g. if it subscribes to one or more topics by using the ```SubscribeFun```.

Your case only requires the ```PublishFun```:
```erlang
Topic = [<<"a">>, <<"b">>,<<"c">>], % a/b/c
Payload = <<"helloworld">>,
PublishFun(Topic, BinaryPayload).
```

Hope this helps.

**Comment by testark** [comment]
@dergraf Thank you very much. As for the `auth_on_publish` hook, I found out later that it will indeed be called if the same plugin also implements `auth_on_subscribe` (even if the only thing it does is to return `next`). I implemented it this way and now it's working ;-)

**Comment by sunnyjain1** [comment]
Hey Dergraf,

Can you tell me what are the default value it takes for other attributes like QoS etc when we publish using PublishFun.

**Comment by dergraf** [comment]
Hi there

Qos=0
Dup=false
Retain=false

Cheers

**Comment by sunnyjain1** [comment]
Is there any other way to publish a message while changing the values of Qos, Dup and Retain ?

**Comment by dergraf** [comment]
Currently not.but we might change this in the future.

**Comment by sunnyjain1** [comment]
I want to change these values. Any ideas on how to to do so??

**Comment by sunnyjain1** [comment]
Can't we use the publish function define in vmq_reg directly. When I write this code.

`Msg = #vmq_msg{routing_key=Lot,payload=Payload,qos=1},`
 `ok = publish(Msg)`

it shows me this error

`unction_clause, trace: [{vmq_reg_trie,match,[undefined,[<<"new">>]],[{file,"/Users/sunnyjain/Desktop/vernemq/_build/default/lib/vmq_server/src/vmq_reg_trie.erl"},{line,200}]},{vmq_reg_trie,fold,4,[{file,"/Users/sunnyjain/Desktop/vernemq/_build/default/lib/vmq_server/src/vmq_reg_trie.erl"},{line,40}]},{vmq_reg,publish,1,[{file,"/Users/sunnyjain/Desktop/vernemq/_build/default/lib/vmq_server/src/vmq_reg.erl"},{line,281}]},{http_to_mqtt_web,loop,2,[{file,"src/http_to_mqtt_web.erl"},{line,48}]},{mochiweb_http,headers,6,[{file,"src/mochiweb_http.erl"},{line,122}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]`

what is the problem here?

**Comment by dergraf** [comment]
I am currently working on a fix for this, which we'll release as soon as possible.

Am 28.02.2016 10:40 schrieb Sunny Jain <notifications@github.com>:

Can't we use the publish function define in vmq_reg directly. When I write this code.

Msg = #vmq_msg{routing_key=Lot,payload=Payload,qos=1},
ok = publish(Msg)

it shows me this error

unction_clause, trace: [{vmq_reg_trie,match,[undefined,[<<"new">>]],[{file,"/Users/sunnyjain/Desktop/vernemq/_build/default/lib/vmq_server/src/vmq_reg_trie.erl"},{line,200}]},{vmq_reg_trie,fold,4,[{file,"/Users/sunnyjain/Desktop/vernemq/_build/default/lib/vmq_server/src/vmq_reg_trie.erl"},{line,40}]},{vmq_reg,publish,1,[{file,"/Users/sunnyjain/Desktop/vernemq/_build/default/lib/vmq_server/src/vmq_reg.erl"},{line,281}]},{http_to_mqtt_web,loop,2,[{file,"src/http_to_mqtt_web.erl"},{line,48}]},{mochiweb_http,headers,6,[{file,"src/mochiweb_http.erl"},{line,122}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]

what is the problem here?

**Comment by sunnyjain1** [comment]
Hello Andre,

   I have added following code in vmq_reg 
   ```
-spec dpe(module()) -> {function()} | {error}.
dpe(Mod) when is_atom(Mod) ->
    %% This Function exports a generic Register, Publish, and Subscribe
    %% Fun, that a plugin can use if needed. Currently all functions
    %% block until the cluster is ready.
    case {vmq_config:get_env(trade_consistency, false),
          vmq_config:get_env(default_reg_view, vmq_reg_trie)} of
        {TradeConsistency, DefaultRegView}
              when is_boolean(TradeConsistency)
                   and is_atom(DefaultRegView) ->
            MountPoint = "",
            PublishFun1 =
            fun([W|_] = Topic, Payload,Qos,Retain) when is_binary(W) and is_binary(Payload) ->
                    wait_til_ready(),
                    Msg = #vmq_msg{routing_key=Topic,
                                   mountpoint=MountPoint,
                                   payload=Payload,
                                   qos=Qos,
                                   msg_ref=vmq_mqtt_fsm:msg_ref(),
                                   dup=false,
                                   retain=Retain,
                                   trade_consistency=TradeConsistency,
                                   reg_view=DefaultRegView
                                  },
                    publish(Msg)
            end,
            {PublishFun1};
    _ ->
        {error}
 end.
```

now I am able to publish. But I want to know if it is the right way to do it.
I am also having little problem while publishing with clean session disabled. When I publish with qos other than 1, it is publishing multiples times.

Here is the [link](https://github.com/sunnyjain1/vmq_server) to my updated vmq_server.
