### ISSUE TITLE
libssll.0.0 is not installed

### ISSUE THREAD

**Issue by khoshbin** [erlio/vernemq#657]
### Environment

- VerneMQ Version:1.3.1-1
- OS:Debian 9.4
- Erlang/OTP version (if building from source):

### Expected behavior

I want to install vernemq in my debian 9 

### Actual behaviour
but it claims that it depends on libssll.0.0 and it is missing and 
I have already done 
apt-get install erlang
It seems that libssll.0.0 is not available in newer Debian versions
Thanks
- Please include minimal steps to reproduce the issue, if possible.

**Comment by larshesel** [comment]
Hi @khoshbin 

At the moment only Debian Jessie is supported and the Jessie package can't be installed on Stretch due to the libssl version issue. To run VerneMQ on Debian Stretch you'd have to build from source (or manually install libssl1.0.0).

I'll add it to our backlog to see if we can create Debian packages for Stretch as well, but I can't say when we'd get around to looking at it.
