### ISSUE TITLE
Provide topic and payload to 'on_offline_message'?

### ISSUE THREAD

**Issue by testark** [erlio/vernemq#78]
It would be great to have a message's topic and payload to be provided to the `on_offline_message` hook (alongside the `SubscriberId` parameter). I guess this would require changes in both `vmq_commons` and `vmq_server` to accomodate for an extra two parameters, but would most certainly come in handy. @ioolkos @dergraf what do you think?

**Comment by ioolkos** [comment]
I second this, if you find it handy. @der_graf, what's your opinion here?
Can we think of use cases for this?

**Comment by testark** [comment]
@ioolkos great :-) Well, our use case is that we need to send some notifications to clients when they receive messages while offline, but (i) only on some specific topics and (ii) including the message's text.

**Comment by dergraf** [comment]
@testark I completely understand your use case. Let me quickly tell the story behind this hook.

When I've originally introduced the ``on_offline_message`` hook I thought about exposing topic and payload. I rejected to do so because it's unclear if topic and payload are enough, e.g why not also expose the QoS, the Dup and Retain flags, or maybe even the internal message reference. 
In the end passing the whole internal message structure ``vmq_msg{}`` to the ``on_offline_hook`` would have addresses all those use cases. However, as mentioned this structure is internal which is why we don't expose it to plugin developers.

Changing hooks is something we could afford today as we haven't reached a stable release yet. But it get's more and more difficult as we reach a more stable API.

How should the hook look like that it serves other use cases too, not only the one of @testark.

RFC!

**Comment by ioolkos** [comment]
I think what we could do is just expose the "MQTT" parts (topic, payload, dup, qos, retain) in this case. This would still keep the internal `#vmq_msg{}` structure protected.

**Comment by dergraf** [comment]
No other comments arrived. let's close it for the moment.

**Comment by testark** [comment]
@dergraf where you expecting any further feedback? I would still love to see this implemented.
