### ISSUE TITLE
Client PUBACK/PUBREC hook - be notified when messages are received by clients

### ISSUE THREAD

**Issue by eladnava** [erlio/vernemq#803]
### Environment

- VerneMQ Version: 1.4.1
- OS: Ubuntu 16.04
- Erlang/OTP version (if building from source):

### Desired behavior

First of all, VerneMQ looks very promising. Thank you for all the work you put into this project.

I think it would be really useful to have a hook for MQTT PUBACK/PUBREC (in QoS 1 and 2), so that when clients receive published messages, we can be notified about it, with message details like topic, subscriber, payload.

### Actual behaviour

Today there does not seem to be a way to do this with the current Publish Flow:
https://vernemq.com/docs/plugindevelopment/publishflow.html

Thanks again! 👍

**Comment by eladnava** [comment]
I believe the hooking point should be here:
https://github.com/erlio/vmq_server/blob/d008c6dcc62fe985d08456caa4024750e1febf38/src/vmq_mqtt_fsm.erl#L281-L308

**Comment by eladnava** [comment]
Hi @larshesel,
That makes complete sense.

The use case here is to be able to **track message delivery to recipients**. Right now publishing to VernemQ is fire-and-forget -- there is no way for an application to find out if publishes made it to any recipients and therefore mark messages as delivered.

I ended up modifying VernemQ and adding the hook in myself. 👍

**Comment by larshesel** [comment]
I think from a broader, more general perspective it would be interesting to be able to track things like these, namely to do proper audit trails: Msg X came was published and was subsequentyl sent to and acknowledged by clients A,B,C etc.

The thing to solve would be how to integrate this with the existing plugin system. Adding a new hook for PUBACK/PUBREL isn't enough as the correlation to the existing publish hooks is missing (they don't expose the message-id), so to make it work either the existing hooks would have to be changed (breaking change) or low-level hooks for the publish action would have to be defined as well. To be able to track end-to-end delivery, something other than the message ids would have to be used (publish-in and publish-out message ids are not correlated), like a global UUID.

Before VerneMQ 2.0 I think the only viable solution would be to add low-level hooks for all the relevant  frames (publish/puback/pubrec/pubrel/pubcom, etc) - I don't see us adding this in the near future as we're working on other things (finalizing MQTTv5 and a new replication layer which will be part of VerneMQ 2.0), but also because of the earlier mentioned reasons.

Btw. I think I have to mention that even with hooks for message delivery it's still no guarantee that the client has actually handled the message at the application layer (there's a classic post about this here: http://www.eejournal.com/2015/05/28/is-exactly-once-delivery-possible-with-mqtt/), just that the client library has done 'the correct thing'. To be sure the message has been handled at the application leve an explicit MQTT reply might be better, though of course this also has costs in terms of complexity and performance.

For VerneMQ 2.0 we should definitely think about how/if we can support audit trails without suffering too much on the performance side.

**Comment by eladnava** [comment]
Awesome, thanks for the detailed explanation and great job with VerneMQ 🎉

**Comment by larshesel** [comment]
Thank you for asking the question - it's always good to get some insights and getting ideas!
