### ISSUE TITLE
Add kickout hook

### ISSUE THREAD

**Issue by boboxiaodd** [erlio/vernemq#813]
### Environment

- VerneMQ Version: 1.4.0
- OS: centos7
- Erlang/OTP version (if building from source):

### Actual behaviour
we use vernemq be a IM server
when set allow_multiple_sessions = off
client A and client B use the same client_id
client A connected,
client B connected and kickout  client A ,  client A disconnected without any info ,  reconnect start, and will kickout client B ...

maybe we can add a hook , when client A will be kickout,  publish a msg to client A (qos 0) ,

**Comment by larshesel** [comment]
Hi,

It would be interesting to know what use case this would solve? Maybe there's another way to achieve what you want to do?

In MQTTv5 this problem is solved as there the broker can send the client a specific MQTT disconnect packet with the reason code 'disconnected due to session take over'. We expect to merge MQTT v5 support to the master branch in one of the following days, see #814 .

**Comment by boboxiaodd** [comment]
Good!
