### ISSUE TITLE
Interested in the disk consequences of various MQTT usage patterns

### ISSUE THREAD

**Issue by yob** [erlio/vernemq#841]
Hi,

I'm evaluating vernemq for an MQTT deployment, and find myself with a few questions I wsan't able to answer from the available documentation.

To be upfront, my production MQTT experience is pretty limited at this stage so apologies if any of my questions are silly.

I'm particularly interested in the expected disk IO and usage we'd expect to see under different MQTT patterns, and whether we can expect the consumed resources to be predictable if our topic, message and session count remain steady. 

1. What messages are written to the msgstore? Everything? All QOS1/2 message? Only QOS1/2 message that a session is expecting to pickup?

2. Once a message is written to the msgstore, when does it get removed - once all sessions subscribed to the relevant topic have connected and retrieved it?

3. `max_offline_messages` sounds like it'd be a useful way to prevent unbounded growth in disk usage if there are sessions that don't check in regularly to pickup messages. Is that number per session or global? What happens when the cap is reached - are new messages skipped, or are old messages removed to make room?
 
4. In general, are there any recommendations for keeping disk IO and usage predictable? My guesses would be along the lines of: send only QOS0 messages? If using QOS1, minimise number of sessions that are offline to reduce the need for offline messages? use persistent_client_expiration to trim stale sessions with uncollected offline messages? Use max_offline_messages to control total storage space required?

5. Would running a single node vs a three-node cluster change the expected disk IO or usage?

Cheers!

**Comment by dergraf** [comment]
Hello @yob. 
Thank you for those questions!

> 1. What messages are written to the msgstore? Everything? All QOS1/2 message? Only QOS1/2 message that a session is expecting to pickup?

Per default all QoS 1 & 2 messages are stored on disk. The message containing payload and publishing flags is stored once, and for every receiving client we store a reference to this message. 

> 2. Once a message is written to the msgstore, when does it get removed - once all sessions subscribed to the relevant topic have connected and retrieved it?

As soon as all the references are deleted we delete the message containing payload and flags.

> 3. `max_offline_messages` sounds like it'd be a useful way to prevent unbounded growth in disk usage if there are sessions that don't check in regularly to pickup messages. Is that number per session or global? What happens when the cap is reached - are new messages skipped, or are old messages removed to make room?

The `max_offline_messages` is configured per session and allows VerneMQ to apply load shedding on a queue by dropping messages (exactly like you outlined). By default VerneMQ will drop the new message, but this behaviour can be changed by the hidden setting `vmq_server.queue_type = lifo` instead of `fifo`. However this will also change the queue behaviour when delivering messages.

> 4. In general, are there any recommendations for keeping disk IO and usage predictable? My guesses would be along the lines of: send only QOS0 messages? If using QOS1, minimise number of sessions that are offline to reduce the need for offline messages? use persistent_client_expiration to trim stale sessions with uncollected offline messages? Use max_offline_messages to control total storage space required?

This is exactly what I would do, ensure with `max_offline_messages` that the offline 'storage' per session has some upper bound and ensure with `persistent_client_expiration` that old, unused sessions are garbage collected. Additionally you may want to set `max_message_size` to control the max message size that you might need to persist. Moreover, using a plugin you would be able to control QoS of publishes and subscribes, enabling that you control, what QoS your clients are using for publishing and or subscribing.
Alternatively, if you want to use the QoS 1 & 2 flows, but don't necessarily require the disk persistence you could completely disable the message store (undocumented, but possible). 

> 5. Would running a single node vs a three-node cluster change the expected disk IO or usage?

Yes, by adding multiple nodes you're able to distribute load among multiple nodes. 


All that said, keep in mind that our replicated storage also uses LevelDB under the hood to store retained messages and subscription data (e..g. which client has which subscriptions on which node). Moreover the replication mechanism builds up a hashtree (which is stored in LevelDB) for efficient synchronization between the cluster nodes.

**Comment by yob** [comment]
Thanks for taking the time to write such detailed responses, it's really helped me build a mental model of how disk persistence is used.
