### ISSUE TITLE
More documentation about clustering / HA setup

### ISSUE THREAD

**Issue by weeco** [erlio/vernemq#846]
Could you provide more docs about Clustering? Specifically I am looking for docs how to achieve a high availability setup with replica (zonal or regional via WAN), implications of node faults, best practices etc.?

For instance:
1. I do see there are config options to accept publish/subscribe/connect if a node fails, they are set to "off" by default. I assume there's a good reason for this behaviour, but what should I do if I need to achieve a high availability setup? What should I look for, how does the architecture look like and how many nodes can fail without having any (temporary) outages?
2. How many nodes should I choose for my cluster? Does it make sense to choose a odd or even number of nodes because of replicated data?
3. Currently I have a cluster setup with 4 nodes (as described here: https://vernemq.com/docs/clustering/). When I perform a rolling update (or if a pod unexpectedly dies) the MQTT service is not available anymore, because just one of these nodes is down. So is this cluster purely used for loadbalancing/performance without having any redundancy?

**Optional:**
Another documentation advice seen from at other message broker docs: A check list before going with your services into production (settings, authentication, what to monitor/benchmark/test)

**Comment by dergraf** [comment]
Hello @weeco 

Thank you for those great questions. First, in order to have a well performing VerneMQ cluster you'd require (more or less) predictable low network latencies. While we know people who are deploying VerneMQ clusters in multiple geographically distributed zones, VerneMQ isn't designed for such deployments. That said, it may work for you or it may not work at all. You've to run your own tests for that.

> 1. I do see there are config options to accept publish/subscribe/connect if a node fails, they are set to "off" by default. I assume there's a good reason for this behaviour, but what should I do if I need to achieve a high availability setup? What should I look for, how does the architecture look like and how many nodes can fail without having any (temporary) outages?

It is a bit more complex then this as from VerneMQ perspective a node fault (e.g. the server explodes in the middle of the night) is the same thing like a network split (e.g. someone cuts the network cables between the two or more nodes). All that VerneMQ sees is that one or more nodes are offline, whereas they should actually be online. Now, if you want to achieve high availability with VerneMQ even in such unhealthy scenarios you should set those `accept_*_during_netsplit` to `on`. However you must be aware of the consequences of such a decision, as you're basically *trading* consistency for higher availability. As a result you're likely going to loose messages due to multiple reasons:

1. the clustering communication buffers were full which resulted in a message drop.
2. a subscription on one node wasn't propagated on time so that a message wasn't routed properly.
3. newly retained messages weren't propagated on time so that new subscriptions won't receive a retained message.

While the first one can be detected using the metric `cluster_bytes_dropped` the second and third one can't be simply detected, especially as it could occur even in a 'healthy' cluster when the nodes aren't yet fully synchronized.

Furthermore the MQTT spec forces the broker to disconnect existing clients if a new client connects with the same client id, which obviously is difficult to do in an unhealthy cluster. This becomes even more tricky when `clean_session=false` is used where VerneMQ would have to migrate messages from the 'old' queue to the 'new' one. Obviously the spec is difficult to guarantee in such a case, which could result in that VerneMQ won't allow the register to happen at all until the the problem is resolved.

> 2. How many nodes should I choose for my cluster? Does it make sense to choose a odd or even number of nodes because of replicated data?

We'd prefer a few powerful nodes than a lot of weak nodes. So, if you could plan the server capacity for a 3 to 10 nodes cluster, I think this would be ideal. But it's difficult to tell without knowing the workload you're planning to have. It doesn't matter if the node count is even or uneven.

> 3. Currently I have a cluster setup with 4 nodes (as described here: https://vernemq.com/docs/clustering/). When I perform a rolling update (or if a pod unexpectedly dies) the MQTT service is not available anymore, because just one of these nodes is down. So is this cluster purely used for loadbalancing/performance without having any redundancy?

Exactly, you'd need to deal with the configurations mentioned in 1) to configure VerneMQ for high availability.

We don't have such a checklist at the moment, but we're happy to provider the commercial services to assist you with the transition from a development to a production deployment.

**Comment by weeco** [comment]
@dergraf Thank you for your great response and explaining the reasons for this behaviour. Also I read other closed issues about clustering / ha and I believe a superset of all these questions / answers would be a great enrichment for your VerneMQ doc page.

**Comment by weeco** [comment]
@dergraf Follow up question: How does the load balancing work. I did a little stress test with 4 nodes in my cluster, each having 1.5 cores assigned. I sent messages at a rate of 3.5k / second at 4 different topics and subscribed to one of the topics which was published to at a rate of 1k / second.

That stress test was done with a single client and I noticed that the CPU usage significantly increased only at one node. See here: https://monosnap.com/direct/9G3w8DIpg1BBtFN2RQNHdsKII4rJBA

Can you explain how vernemq performs the loadbalancing?

**Comment by dergraf** [comment]
VerneMQ relies on a external load balancer such as HAProxy to equally
balance connections to all the nodes.

A related topic would be the shared subscription feature
https://vernemq.com/docs/configuration/shared_subscriptions.html


Weeco <notifications@github.com> schrieb am Mi., 19. Sep. 2018, 16:28:
